
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.correios.bsb.sigep.master.bean.cliente;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-12-21T22:37:58.780-03:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "AtendeClienteService",
                      portName = "AtendeClientePort",
                      targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/",
                      wsdlLocation = "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl",
                      endpointInterface = "br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente")

public class AtendeClientePortImpl implements AtendeCliente {

    private static final Logger LOG = Logger.getLogger(AtendeClientePortImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaServicosAdicionaisAtivos(java.lang.String usuario, java.lang.String senha)*
     */
    public java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML> buscaServicosAdicionaisAtivos(java.lang.String usuario, java.lang.String senha) throws SQLException_Exception,  SigepClienteException   {
        LOG.info("Executing operation buscaServicosAdicionaisAtivos");
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML> _return = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML>();
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML _returnVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML();
            _returnVal1.setCategoria("Categoria-1337690155");
            _returnVal1.setCodigo("Codigo98170850");
            _returnVal1.setDescricao("Descricao1337520302");
            _returnVal1.setMaximoValorDeclarado(Double.valueOf(0.8640333459604327));
            _returnVal1.setMinimoValorDeclarado(Double.valueOf(0.05738196355978442));
            _returnVal1.setSigla("Sigla-552851479");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#fechaPlp(java.lang.String xml, java.lang.Long idPlpCliente, java.lang.String cartaoPostagem, java.lang.String faixaEtiquetas, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.Long fechaPlp(java.lang.String xml, java.lang.Long idPlpCliente, java.lang.String cartaoPostagem, java.lang.String faixaEtiquetas, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation fechaPlp");
        System.out.println(xml);
        System.out.println(idPlpCliente);
        System.out.println(cartaoPostagem);
        System.out.println(faixaEtiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Long _return = Long.valueOf(-8447721011724028553l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#validaPlp(long cliente, java.lang.String numero, long diretoria, java.lang.String cartao, java.lang.String unidadePostagem, java.lang.Long servico, java.util.List<java.lang.String> servicosAdicionais, java.lang.String usuario, java.lang.String senha)*
     */
    public boolean validaPlp(long cliente, java.lang.String numero, long diretoria, java.lang.String cartao, java.lang.String unidadePostagem, java.lang.Long servico, java.util.List<java.lang.String> servicosAdicionais, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation validaPlp");
        System.out.println(cliente);
        System.out.println(numero);
        System.out.println(diretoria);
        System.out.println(cartao);
        System.out.println(unidadePostagem);
        System.out.println(servico);
        System.out.println(servicosAdicionais);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#calculaTarifaServico(java.lang.String codAdministrativo, java.lang.String usuario, java.lang.String senha, java.lang.String codServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String peso, java.lang.Integer codFormato, java.lang.Double comprimento, java.lang.Double altura, java.lang.Double largura, java.lang.Double diametro, java.lang.String codMaoPropria, java.lang.Double valorDeclarado, java.lang.String codAvisoRecebimento)*
     */
    public java.lang.String calculaTarifaServico(java.lang.String codAdministrativo, java.lang.String usuario, java.lang.String senha, java.lang.String codServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String peso, java.lang.Integer codFormato, java.lang.Double comprimento, java.lang.Double altura, java.lang.Double largura, java.lang.Double diametro, java.lang.String codMaoPropria, java.lang.Double valorDeclarado, java.lang.String codAvisoRecebimento) throws SigepClienteException,  Exception_Exception,  AutenticacaoException   {
        LOG.info("Executing operation calculaTarifaServico");
        System.out.println(codAdministrativo);
        System.out.println(usuario);
        System.out.println(senha);
        System.out.println(codServico);
        System.out.println(cepOrigem);
        System.out.println(cepDestino);
        System.out.println(peso);
        System.out.println(codFormato);
        System.out.println(comprimento);
        System.out.println(altura);
        System.out.println(largura);
        System.out.println(diametro);
        System.out.println(codMaoPropria);
        System.out.println(valorDeclarado);
        System.out.println(codAvisoRecebimento);
        try {
            java.lang.String _return = "_return-1715590817";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new Exception_Exception("Exception...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#verificaSeTodosObjetosCancelados(java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> arg0)*
     */
    public boolean verificaSeTodosObjetosCancelados(java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> arg0) throws SigepClienteException   {
        LOG.info("Executing operation verificaSeTodosObjetosCancelados");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#cancelarObjeto(java.lang.Long idPlp, java.lang.String numeroEtiqueta, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.Boolean cancelarObjeto(java.lang.Long idPlp, java.lang.String numeroEtiqueta, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  Exception_Exception,  AutenticacaoException   {
        LOG.info("Executing operation cancelarObjeto");
        System.out.println(idPlp);
        System.out.println(numeroEtiqueta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new Exception_Exception("Exception...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#pesquisarParametrosPorDescricao(java.lang.String prefix)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO pesquisarParametrosPorDescricao(java.lang.String prefix) {
        LOG.info("Executing operation pesquisarParametrosPorDescricao");
        System.out.println(prefix);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO _return = new br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO();
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnAltura = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnAltura.setMaximo(new java.math.BigDecimal("-7196992981334225063.349733033793025774"));
            _returnAltura.setMinimo(new java.math.BigDecimal("-2658789278481657569.7452157593678608456"));
            _return.setAltura(_returnAltura);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnComprimento = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnComprimento.setMaximo(new java.math.BigDecimal("4506199330694394053.3801494809029065324"));
            _returnComprimento.setMinimo(new java.math.BigDecimal("-3609815147928079915.7115496250566282771"));
            _return.setComprimento(_returnComprimento);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnDiametro = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnDiametro.setMaximo(new java.math.BigDecimal("-3955720463951522262.6623655150576635495"));
            _returnDiametro.setMinimo(new java.math.BigDecimal("2626341525137769758.4171617443092661876"));
            _return.setDiametro(_returnDiametro);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnLargura = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnLargura.setMaximo(new java.math.BigDecimal("-8530630617775521561.68544589990187484"));
            _returnLargura.setMinimo(new java.math.BigDecimal("-2060963021420622274.5049876314827699587"));
            _return.setLargura(_returnLargura);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnPeso = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnPeso.setMaximo(new java.math.BigDecimal("-1109326943605509567.7517095884252553668"));
            _returnPeso.setMinimo(new java.math.BigDecimal("8722194807414827673.2021995859506810393"));
            _return.setPeso(_returnPeso);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnSoma = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnSoma.setMaximo(new java.math.BigDecimal("6180200962282832863.1084927428668237544"));
            _returnSoma.setMinimo(new java.math.BigDecimal("1041715598698345019.74606928272079689"));
            _return.setSoma(_returnSoma);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#atualizaPagamentoNaEntrega(java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String atualizaPagamentoNaEntrega(java.lang.String usuario, java.lang.String senha) throws SQLException_Exception,  SigepClienteException   {
        LOG.info("Executing operation atualizaPagamentoNaEntrega");
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return-793498284";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#obterClienteAtualizacao(java.lang.String cnpjCliente, java.lang.String usuario, java.lang.String senha)*
     */
    public javax.xml.datatype.XMLGregorianCalendar obterClienteAtualizacao(java.lang.String cnpjCliente, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation obterClienteAtualizacao");
        System.out.println(cnpjCliente);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.793-03:00");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#verificaDisponibilidadeServico(java.lang.Integer codAdministrativo, java.lang.String numeroServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String verificaDisponibilidadeServico(java.lang.Integer codAdministrativo, java.lang.String numeroServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation verificaDisponibilidadeServico");
        System.out.println(codAdministrativo);
        System.out.println(numeroServico);
        System.out.println(cepOrigem);
        System.out.println(cepDestino);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return-238153650";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#fechaPlpVariosServicos(java.lang.String xml, java.lang.Long idPlpCliente, java.lang.String cartaoPostagem, java.util.List<java.lang.String> listaEtiquetas, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.Long fechaPlpVariosServicos(java.lang.String xml, java.lang.Long idPlpCliente, java.lang.String cartaoPostagem, java.util.List<java.lang.String> listaEtiquetas, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation fechaPlpVariosServicos");
        System.out.println(xml);
        System.out.println(idPlpCliente);
        System.out.println(cartaoPostagem);
        System.out.println(listaEtiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Long _return = Long.valueOf(3410389152852147057l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#geraDigitoVerificadorEtiquetas(java.util.List<java.lang.String> etiquetas, java.lang.String usuario, java.lang.String senha)*
     */
    public java.util.List<java.lang.Integer> geraDigitoVerificadorEtiquetas(java.util.List<java.lang.String> etiquetas, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation geraDigitoVerificadorEtiquetas");
        System.out.println(etiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<java.lang.Integer> _return = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnVal1 = Integer.valueOf(-1512330963);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#obterEmbalagemLRS()*
     */
    public java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster> obterEmbalagemLRS() throws SigepClienteException   {
        LOG.info("Executing operation obterEmbalagemLRS");
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster> _return = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster>();
            br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster _returnVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster();
            _returnVal1.setCodigo("Codigo806365265");
            _returnVal1.setNome("Nome1154444229");
            _returnVal1.setTipo("Tipo-926780281");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#validaEtiquetaPLP(java.lang.String numeroEtiqueta, java.lang.Long idPlp, java.lang.String usuario, java.lang.String senha)*
     */
    public boolean validaEtiquetaPLP(java.lang.String numeroEtiqueta, java.lang.Long idPlp, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation validaEtiquetaPLP");
        System.out.println(numeroEtiqueta);
        System.out.println(idPlp);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaServicosValorDeclarado(java.lang.String usuario, java.lang.String senha)*
     */
    public java.util.List<java.lang.String> buscaServicosValorDeclarado(java.lang.String usuario, java.lang.String senha) throws SQLException_Exception,  SigepClienteException   {
        LOG.info("Executing operation buscaServicosValorDeclarado");
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-221435010";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#consultaCEP(java.lang.String cep)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP consultaCEP(java.lang.String cep) throws SQLException_Exception,  SigepClienteException   {
        LOG.info("Executing operation consultaCEP");
        System.out.println(cep);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _return = new br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP();
            _return.setBairro("Bairro-581149964");
            _return.setCep("Cep-1192209405");
            _return.setCidade("Cidade1734468178");
            _return.setComplemento2("Complemento2879115182");
            _return.setEnd("End-595068452");
            _return.setUf("Uf-862353671");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _returnUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
            br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP _returnUnidadesPostagemVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP();
            _returnUnidadesPostagemVal1.setDiretoriaRegional("DiretoriaRegional-461832654");
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _returnUnidadesPostagemVal1Endereco = new br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP();
            _returnUnidadesPostagemVal1Endereco.setBairro("Bairro-1599149245");
            _returnUnidadesPostagemVal1Endereco.setCep("Cep-336275306");
            _returnUnidadesPostagemVal1Endereco.setCidade("Cidade1172463632");
            _returnUnidadesPostagemVal1Endereco.setComplemento2("Complemento2-1197478470");
            _returnUnidadesPostagemVal1Endereco.setEnd("End-1565976761");
            _returnUnidadesPostagemVal1Endereco.setUf("Uf1803765559");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _returnUnidadesPostagemVal1EnderecoUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
            _returnUnidadesPostagemVal1Endereco.getUnidadesPostagem().addAll(_returnUnidadesPostagemVal1EnderecoUnidadesPostagem);
            _returnUnidadesPostagemVal1.setEndereco(_returnUnidadesPostagemVal1Endereco);
            _returnUnidadesPostagemVal1.setId("Id1420720192");
            _returnUnidadesPostagemVal1.setNome("Nome896002393");
            _returnUnidadesPostagemVal1.setStatus("Status1042399189");
            _returnUnidadesPostagemVal1.setTipo("Tipo934498407");
            _returnUnidadesPostagem.add(_returnUnidadesPostagemVal1);
            _return.getUnidadesPostagem().addAll(_returnUnidadesPostagem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#integrarUsuarioScol(java.lang.Integer codAdministrativo, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.Boolean integrarUsuarioScol(java.lang.Integer codAdministrativo, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation integrarUsuarioScol");
        System.out.println(codAdministrativo);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#pesquisarDimensoesServico(java.lang.String codigo, java.lang.String embalagem)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO pesquisarDimensoesServico(java.lang.String codigo, java.lang.String embalagem) {
        LOG.info("Executing operation pesquisarDimensoesServico");
        System.out.println(codigo);
        System.out.println(embalagem);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO _return = new br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO();
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnAltura = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnAltura.setMaximo(new java.math.BigDecimal("2208834835149521591.1122321219677465555"));
            _returnAltura.setMinimo(new java.math.BigDecimal("-3859260572787696560.2695134047706221362"));
            _return.setAltura(_returnAltura);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnComprimento = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnComprimento.setMaximo(new java.math.BigDecimal("8459404159124017852.2062325889738174228"));
            _returnComprimento.setMinimo(new java.math.BigDecimal("-7040760152980984011.1839912962688994781"));
            _return.setComprimento(_returnComprimento);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnDiametro = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnDiametro.setMaximo(new java.math.BigDecimal("-5002978169161209416.7528726350007686924"));
            _returnDiametro.setMinimo(new java.math.BigDecimal("8449872420587842279.6384581843864226768"));
            _return.setDiametro(_returnDiametro);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnLargura = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnLargura.setMaximo(new java.math.BigDecimal("-8823909925593413584.7459241523892171381"));
            _returnLargura.setMinimo(new java.math.BigDecimal("1270313097335201327.6205765393061928831"));
            _return.setLargura(_returnLargura);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnPeso = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnPeso.setMaximo(new java.math.BigDecimal("5249292470340283729.6036003301720215378"));
            _returnPeso.setMinimo(new java.math.BigDecimal("1987945323251719353.4405322579862578524"));
            _return.setPeso(_returnPeso);
            br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO _returnSoma = new br.com.correios.bsb.sigep.master.bean.cliente.MedidaTO();
            _returnSoma.setMaximo(new java.math.BigDecimal("-6543387092254505114.4637115225165503747"));
            _returnSoma.setMinimo(new java.math.BigDecimal("6449761655025039253.5133135598265629061"));
            _return.setSoma(_returnSoma);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#pesquisarEmbalagensPorServico(java.lang.String codigo)*
     */
    public java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem> pesquisarEmbalagensPorServico(java.lang.String codigo) {
        LOG.info("Executing operation pesquisarEmbalagensPorServico");
        System.out.println(codigo);
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem> _return = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem>();
            br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem _returnVal1 = br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem.RL;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#atualizaRemessaAgrupada(java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String atualizaRemessaAgrupada(java.lang.String usuario, java.lang.String senha) throws SQLException_Exception,  SigepClienteException   {
        LOG.info("Executing operation atualizaRemessaAgrupada");
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return-1877216157";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#solicitaPLP(java.lang.Long idPlpMaster, java.lang.String numEtiqueta, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String solicitaPLP(java.lang.Long idPlpMaster, java.lang.String numEtiqueta, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation solicitaPLP");
        System.out.println(idPlpMaster);
        System.out.println(numEtiqueta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return1837019073";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#getStatusCartaoPostagem(java.lang.String numeroCartaoPostagem, java.lang.String usuario, java.lang.String senha)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.StatusCartao getStatusCartaoPostagem(java.lang.String numeroCartaoPostagem, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation getStatusCartaoPostagem");
        System.out.println(numeroCartaoPostagem);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.StatusCartao _return = br.com.correios.bsb.sigep.master.bean.cliente.StatusCartao.IRREGULAR;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#verificaModalTransporte(java.lang.String codigoServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String verificaModalTransporte(java.lang.String codigoServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation verificaModalTransporte");
        System.out.println(codigoServico);
        System.out.println(cepOrigem);
        System.out.println(cepDestino);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return471746220";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaDataAtual()*
     */
    public javax.xml.datatype.XMLGregorianCalendar buscaDataAtual() {
        LOG.info("Executing operation buscaDataAtual");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.799-03:00");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaTarifaVale(java.lang.String codAdministrativo, java.lang.String usuario, java.lang.String senha, java.lang.String codServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String peso, java.lang.Integer codFormato, java.lang.Double comprimento, java.lang.Double altura, java.lang.Double largura, java.lang.Double valorDeclarado, java.lang.String servicoAdicional)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.ValePostal buscaTarifaVale(java.lang.String codAdministrativo, java.lang.String usuario, java.lang.String senha, java.lang.String codServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String peso, java.lang.Integer codFormato, java.lang.Double comprimento, java.lang.Double altura, java.lang.Double largura, java.lang.Double valorDeclarado, java.lang.String servicoAdicional) throws SigepClienteException,  Exception_Exception,  AutenticacaoException   {
        LOG.info("Executing operation buscaTarifaVale");
        System.out.println(codAdministrativo);
        System.out.println(usuario);
        System.out.println(senha);
        System.out.println(codServico);
        System.out.println(cepOrigem);
        System.out.println(cepDestino);
        System.out.println(peso);
        System.out.println(codFormato);
        System.out.println(comprimento);
        System.out.println(altura);
        System.out.println(largura);
        System.out.println(valorDeclarado);
        System.out.println(servicoAdicional);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ValePostal _return = new br.com.correios.bsb.sigep.master.bean.cliente.ValePostal();
            _return.setCidNoCidade("CidNoCidade1019266486");
            _return.setCtcCoAadministrativo("CtcCoAadministrativo-1869560015");
            _return.setCtcNuContrato(Long.valueOf(507946219933538039l));
            _return.setCtcNuContratoEct(Long.valueOf(4429732640309937976l));
            _return.setCvpEdBairro("CvpEdBairro858287360");
            _return.setCvpEdCliente("CvpEdCliente-1312822341");
            _return.setCvpEdComplemento("CvpEdComplemento-1303577482");
            _return.setCvpEdNumero("CvpEdNumero-889745871");
            _return.setCvpNoCliente("CvpNoCliente1360895177");
            _return.setCvpNuCep(Long.valueOf(6177474476492316688l));
            _return.setDescricaoErro("DescricaoErro-1765356514");
            _return.setEstSgEstado("EstSgEstado1644070034");
            _return.setMonVarTarifaAdicional(1256632659);
            _return.setMonVarTarifaServico(-1030563824);
            _return.setMonVarValorDescontos(1645146040);
            _return.setMonVarValorImposto(-1091360881);
            _return.setPrsCoProdutoServico(Long.valueOf(-3515611598113297064l));
            _return.setPveNu(Long.valueOf(-6630969052839924971l));
            _return.setPveOrgNuAgencia(Long.valueOf(-456587587989138395l));
            _return.setPveOrgNuAgenciaDes(Long.valueOf(-4650762989871469405l));
            _return.setPveOrgNuAgenciaOri(Long.valueOf(5663646391575075768l));
            _return.setRetornaCodErro(313344604);
            _return.setSitNoSituacao("SitNoSituacao571438118");
            _return.setTlgTxDescricao("TlgTxDescricao1556891976");
            _return.setVapDhTransacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.800-03:00"));
            _return.setVapNuEtiquetaEncomenda("VapNuEtiquetaEncomenda-599854024");
            _return.setVapVrCobradoEct(Double.valueOf(0.6171449481096886));
            _return.setVapVrNominal(Double.valueOf(0.34006911310414867));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new Exception_Exception("Exception...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#validarPostagemSimultanea(java.lang.Integer codAdministrativo, java.lang.Integer codigoServico, java.lang.String idCartaoPostagem, java.lang.String cepDestinatario, br.com.correios.bsb.sigep.master.bean.cliente.ColetaSimultanea coleta, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.Boolean validarPostagemSimultanea(java.lang.Integer codAdministrativo, java.lang.Integer codigoServico, java.lang.String idCartaoPostagem, java.lang.String cepDestinatario, br.com.correios.bsb.sigep.master.bean.cliente.ColetaSimultanea coleta, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation validarPostagemSimultanea");
        System.out.println(codAdministrativo);
        System.out.println(codigoServico);
        System.out.println(idCartaoPostagem);
        System.out.println(cepDestinatario);
        System.out.println(coleta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#getStatusPLP(java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> arg0, java.lang.String arg1)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp getStatusPLP(java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> arg0, java.lang.String arg1) throws SigepClienteException   {
        LOG.info("Executing operation getStatusPLP");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _return = br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp.ABERTA;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#pesquisarServicosAdicionais(java.lang.String codigo)*
     */
    public java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO> pesquisarServicosAdicionais(java.lang.String codigo) {
        LOG.info("Executing operation pesquisarServicosAdicionais");
        System.out.println(codigo);
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO> _return = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO>();
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO _returnVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO();
            _returnVal1.setCategoria("Categoria377549338");
            _returnVal1.setCodigo("Codigo244702258");
            _returnVal1.setSigla("Sigla1593943460");
            _returnVal1.setTipo("Tipo-1304641406");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaServicosXServicosAdicionais(java.lang.String usuario, java.lang.String senha)*
     */
    public java.util.List<java.lang.String> buscaServicosXServicosAdicionais(java.lang.String usuario, java.lang.String senha) throws SQLException_Exception,  SigepClienteException   {
        LOG.info("Executing operation buscaServicosXServicosAdicionais");
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal222036631";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#cancelarPedidoScol(java.lang.String codAdministrativo, java.lang.String idPostagem, java.lang.String tipo, java.lang.String usuario, java.lang.String senha)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.RetornoCancelamento cancelarPedidoScol(java.lang.String codAdministrativo, java.lang.String idPostagem, java.lang.String tipo, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation cancelarPedidoScol");
        System.out.println(codAdministrativo);
        System.out.println(idPostagem);
        System.out.println(tipo);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.RetornoCancelamento _return = new br.com.correios.bsb.sigep.master.bean.cliente.RetornoCancelamento();
            _return.setCodErro("CodErro-1884050180");
            _return.setCodigoAdministrativo("CodigoAdministrativo1060331016");
            _return.setData("Data-821846842");
            _return.setHora("Hora1714064736");
            _return.setMsgErro("MsgErro185170142");
            br.com.correios.bsb.sigep.master.bean.cliente.ObjetoSimplificado _returnObjetoPostal = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoSimplificado();
            _returnObjetoPostal.setDatahoraCancelamento("DatahoraCancelamento-2068385321");
            _returnObjetoPostal.setNumeroPedido(Integer.valueOf(-1651067973));
            _returnObjetoPostal.setStatusPedido("StatusPedido158252730");
            _return.setObjetoPostal(_returnObjetoPostal);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#bloquearObjeto(java.lang.String numeroEtiqueta, java.lang.Long idPlp, br.com.correios.bsb.sigep.master.bean.cliente.TipoBloqueio tipoBloqueio, br.com.correios.bsb.sigep.master.bean.cliente.Acao acao, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String bloquearObjeto(java.lang.String numeroEtiqueta, java.lang.Long idPlp, br.com.correios.bsb.sigep.master.bean.cliente.TipoBloqueio tipoBloqueio, br.com.correios.bsb.sigep.master.bean.cliente.Acao acao, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation bloquearObjeto");
        System.out.println(numeroEtiqueta);
        System.out.println(idPlp);
        System.out.println(tipoBloqueio);
        System.out.println(acao);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return48320409";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaContrato(java.lang.String numero, long diretoria, java.lang.String usuario, java.lang.String senha)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP buscaContrato(java.lang.String numero, long diretoria, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation buscaContrato");
        System.out.println(numero);
        System.out.println(diretoria);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP _return = new br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP();
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP> _returnCartoesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP>();
            br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP _returnCartoesPostagemVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP();
            _returnCartoesPostagemVal1.setCodigoAdministrativo("CodigoAdministrativo-915492077");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _returnCartoesPostagemVal1Contratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
            _returnCartoesPostagemVal1.getContratos().addAll(_returnCartoesPostagemVal1Contratos);
            _returnCartoesPostagemVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.803-03:00"));
            _returnCartoesPostagemVal1.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.804-03:00"));
            _returnCartoesPostagemVal1.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.804-03:00"));
            _returnCartoesPostagemVal1.setDatajAtualizacao(Integer.valueOf(1561432424));
            _returnCartoesPostagemVal1.setDatajVigenciaFim(Integer.valueOf(463455864));
            _returnCartoesPostagemVal1.setDatajVigenciaInicio(Integer.valueOf(-1709606802));
            _returnCartoesPostagemVal1.setDescricaoStatusCartao("DescricaoStatusCartao337052158");
            _returnCartoesPostagemVal1.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica-2015530209");
            _returnCartoesPostagemVal1.setHorajAtualizacao(Integer.valueOf(617298352));
            _returnCartoesPostagemVal1.setNumero("Numero-1754086466");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _returnCartoesPostagemVal1Servicos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP>();
            _returnCartoesPostagemVal1.getServicos().addAll(_returnCartoesPostagemVal1Servicos);
            _returnCartoesPostagemVal1.setStatusCartaoPostagem("StatusCartaoPostagem422078448");
            _returnCartoesPostagemVal1.setStatusCodigo("StatusCodigo729885629");
            _returnCartoesPostagemVal1.setUnidadeGenerica("UnidadeGenerica-1581360208");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _returnCartoesPostagemVal1UnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
            _returnCartoesPostagemVal1.getUnidadesPostagem().addAll(_returnCartoesPostagemVal1UnidadesPostagem);
            _returnCartoesPostagem.add(_returnCartoesPostagemVal1);
            _return.getCartoesPostagem().addAll(_returnCartoesPostagem);
            br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP _returnCliente = new br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP();
            _returnCliente.setCnpj("Cnpj-230698252");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _returnClienteContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP _returnClienteContratosVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP();
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP> _returnClienteContratosVal1CartoesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP>();
            _returnClienteContratosVal1.getCartoesPostagem().addAll(_returnClienteContratosVal1CartoesPostagem);
            br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP _returnClienteContratosVal1Cliente = new br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP();
            _returnClienteContratosVal1Cliente.setCnpj("Cnpj-1707078806");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _returnClienteContratosVal1ClienteContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
            _returnClienteContratosVal1Cliente.getContratos().addAll(_returnClienteContratosVal1ClienteContratos);
            _returnClienteContratosVal1Cliente.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.804-03:00"));
            _returnClienteContratosVal1Cliente.setDatajAtualizacao(Integer.valueOf(-1160476624));
            _returnClienteContratosVal1Cliente.setDescricaoStatusCliente("DescricaoStatusCliente-773422542");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta> _returnClienteContratosVal1ClienteGerenteConta = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta>();
            _returnClienteContratosVal1Cliente.getGerenteConta().addAll(_returnClienteContratosVal1ClienteGerenteConta);
            _returnClienteContratosVal1Cliente.setHorajAtualizacao(Long.valueOf(-8293806828650573462l));
            _returnClienteContratosVal1Cliente.setId(-5159163399185692465l);
            _returnClienteContratosVal1Cliente.setInscricaoEstadual("InscricaoEstadual890413802");
            _returnClienteContratosVal1Cliente.setNome("Nome1918943232");
            _returnClienteContratosVal1Cliente.setStatusCodigo("StatusCodigo1033994098");
            _returnClienteContratosVal1.setCliente(_returnClienteContratosVal1Cliente);
            _returnClienteContratosVal1.setCodigoCliente(8392044148144491039l);
            _returnClienteContratosVal1.setCodigoDiretoria("CodigoDiretoria1285781025");
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERPPK _returnClienteContratosVal1ContratoPK = new br.com.correios.bsb.sigep.master.bean.cliente.ContratoERPPK();
            _returnClienteContratosVal1ContratoPK.setDiretoria(-3087161942104850035l);
            _returnClienteContratosVal1ContratoPK.setNumero("Numero1620610475");
            _returnClienteContratosVal1.setContratoPK(_returnClienteContratosVal1ContratoPK);
            _returnClienteContratosVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.804-03:00"));
            _returnClienteContratosVal1.setDataAtualizacaoDDMMYYYY("DataAtualizacaoDDMMYYYY-1299460934");
            _returnClienteContratosVal1.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.804-03:00"));
            _returnClienteContratosVal1.setDataVigenciaFimDDMMYYYY("DataVigenciaFimDDMMYYYY1283441904");
            _returnClienteContratosVal1.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.805-03:00"));
            _returnClienteContratosVal1.setDataVigenciaInicioDDMMYYYY("DataVigenciaInicioDDMMYYYY922877135");
            _returnClienteContratosVal1.setDatajAtualizacao(Integer.valueOf(-1511531214));
            _returnClienteContratosVal1.setDatajVigenciaFim(Integer.valueOf(-854592248));
            _returnClienteContratosVal1.setDatajVigenciaInicio(Integer.valueOf(-1103107515));
            _returnClienteContratosVal1.setDescricaoDiretoriaRegional("DescricaoDiretoriaRegional1400749078");
            _returnClienteContratosVal1.setDescricaoStatus("DescricaoStatus1922153463");
            br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP _returnClienteContratosVal1DiretoriaRegional = new br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP();
            _returnClienteContratosVal1DiretoriaRegional.setDiretoriaRegional("DiretoriaRegional-687036378");
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _returnClienteContratosVal1DiretoriaRegionalEndereco = new br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP();
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setBairro("Bairro-614231883");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setCep("Cep280627682");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setCidade("Cidade-1765755778");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setComplemento2("Complemento2-1752089625");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setEnd("End1674852112");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setUf("Uf-451228789");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _returnClienteContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
            _returnClienteContratosVal1DiretoriaRegionalEndereco.getUnidadesPostagem().addAll(_returnClienteContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem);
            _returnClienteContratosVal1DiretoriaRegional.setEndereco(_returnClienteContratosVal1DiretoriaRegionalEndereco);
            _returnClienteContratosVal1DiretoriaRegional.setId("Id-1313381773");
            _returnClienteContratosVal1DiretoriaRegional.setNome("Nome-585649947");
            _returnClienteContratosVal1DiretoriaRegional.setStatus("Status1281221460");
            _returnClienteContratosVal1DiretoriaRegional.setTipo("Tipo149409652");
            _returnClienteContratosVal1.setDiretoriaRegional(_returnClienteContratosVal1DiretoriaRegional);
            _returnClienteContratosVal1.setHorajAtualizacao(Integer.valueOf(-1946044726));
            _returnClienteContratosVal1.setStatusCodigo("StatusCodigo820448730");
            _returnClienteContratos.add(_returnClienteContratosVal1);
            _returnCliente.getContratos().addAll(_returnClienteContratos);
            _returnCliente.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.805-03:00"));
            _returnCliente.setDatajAtualizacao(Integer.valueOf(-2029159050));
            _returnCliente.setDescricaoStatusCliente("DescricaoStatusCliente817203840");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta> _returnClienteGerenteConta = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta>();
            br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta _returnClienteGerenteContaVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta();
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP> _returnClienteGerenteContaVal1ClientesVisiveis = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP>();
            _returnClienteGerenteContaVal1.getClientesVisiveis().addAll(_returnClienteGerenteContaVal1ClientesVisiveis);
            _returnClienteGerenteContaVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.805-03:00"));
            _returnClienteGerenteContaVal1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.805-03:00"));
            _returnClienteGerenteContaVal1.setDataSenha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.806-03:00"));
            _returnClienteGerenteContaVal1.setLogin("Login-818685401");
            _returnClienteGerenteContaVal1.setMatricula("Matricula-17851347");
            _returnClienteGerenteContaVal1.setSenha("Senha181637729");
            br.com.correios.bsb.sigep.master.bean.cliente.StatusGerente _returnClienteGerenteContaVal1Status = br.com.correios.bsb.sigep.master.bean.cliente.StatusGerente.ATIVO;
            _returnClienteGerenteContaVal1.setStatus(_returnClienteGerenteContaVal1Status);
            br.com.correios.bsb.sigep.master.bean.cliente.TipoGerente _returnClienteGerenteContaVal1TipoGerente = br.com.correios.bsb.sigep.master.bean.cliente.TipoGerente.GERENTE_CONTA;
            _returnClienteGerenteContaVal1.setTipoGerente(_returnClienteGerenteContaVal1TipoGerente);
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UsuarioInstalacao> _returnClienteGerenteContaVal1UsuariosInstalacao = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UsuarioInstalacao>();
            _returnClienteGerenteContaVal1.getUsuariosInstalacao().addAll(_returnClienteGerenteContaVal1UsuariosInstalacao);
            _returnClienteGerenteContaVal1.setValidade("Validade727046608");
            _returnClienteGerenteConta.add(_returnClienteGerenteContaVal1);
            _returnCliente.getGerenteConta().addAll(_returnClienteGerenteConta);
            _returnCliente.setHorajAtualizacao(Long.valueOf(2045130376708412799l));
            _returnCliente.setId(-2822269337113840568l);
            _returnCliente.setInscricaoEstadual("InscricaoEstadual215573750");
            _returnCliente.setNome("Nome913088071");
            _returnCliente.setStatusCodigo("StatusCodigo1666394411");
            _return.setCliente(_returnCliente);
            _return.setCodigoCliente(-4640711972348357644l);
            _return.setCodigoDiretoria("CodigoDiretoria-748481148");
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERPPK _returnContratoPK = new br.com.correios.bsb.sigep.master.bean.cliente.ContratoERPPK();
            _returnContratoPK.setDiretoria(-4414413529013131501l);
            _returnContratoPK.setNumero("Numero1413955631");
            _return.setContratoPK(_returnContratoPK);
            _return.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.806-03:00"));
            _return.setDataAtualizacaoDDMMYYYY("DataAtualizacaoDDMMYYYY-1413171167");
            _return.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.806-03:00"));
            _return.setDataVigenciaFimDDMMYYYY("DataVigenciaFimDDMMYYYY-309831168");
            _return.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.806-03:00"));
            _return.setDataVigenciaInicioDDMMYYYY("DataVigenciaInicioDDMMYYYY-92099160");
            _return.setDatajAtualizacao(Integer.valueOf(536343911));
            _return.setDatajVigenciaFim(Integer.valueOf(-1496851840));
            _return.setDatajVigenciaInicio(Integer.valueOf(-1517516996));
            _return.setDescricaoDiretoriaRegional("DescricaoDiretoriaRegional-1719294848");
            _return.setDescricaoStatus("DescricaoStatus1767138222");
            br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP _returnDiretoriaRegional = new br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP();
            _returnDiretoriaRegional.setDiretoriaRegional("DiretoriaRegional1301962926");
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _returnDiretoriaRegionalEndereco = new br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP();
            _returnDiretoriaRegionalEndereco.setBairro("Bairro1098598485");
            _returnDiretoriaRegionalEndereco.setCep("Cep-389687027");
            _returnDiretoriaRegionalEndereco.setCidade("Cidade-665785303");
            _returnDiretoriaRegionalEndereco.setComplemento2("Complemento2-715504169");
            _returnDiretoriaRegionalEndereco.setEnd("End-1403687056");
            _returnDiretoriaRegionalEndereco.setUf("Uf-811954924");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _returnDiretoriaRegionalEnderecoUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
            _returnDiretoriaRegionalEndereco.getUnidadesPostagem().addAll(_returnDiretoriaRegionalEnderecoUnidadesPostagem);
            _returnDiretoriaRegional.setEndereco(_returnDiretoriaRegionalEndereco);
            _returnDiretoriaRegional.setId("Id1892595223");
            _returnDiretoriaRegional.setNome("Nome919250683");
            _returnDiretoriaRegional.setStatus("Status453902628");
            _returnDiretoriaRegional.setTipo("Tipo530588285");
            _return.setDiretoriaRegional(_returnDiretoriaRegional);
            _return.setHorajAtualizacao(Integer.valueOf(1087770643));
            _return.setStatusCodigo("StatusCodigo1933722849");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#solicitaEtiquetas(java.lang.String tipoDestinatario, java.lang.String identificador, java.lang.Long idServico, java.lang.Integer qtdEtiquetas, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String solicitaEtiquetas(java.lang.String tipoDestinatario, java.lang.String identificador, java.lang.Long idServico, java.lang.Integer qtdEtiquetas, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation solicitaEtiquetas");
        System.out.println(tipoDestinatario);
        System.out.println(identificador);
        System.out.println(idServico);
        System.out.println(qtdEtiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return331923808";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#solicitaXmlPlp(java.lang.Long idPlpMaster, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String solicitaXmlPlp(java.lang.Long idPlpMaster, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation solicitaXmlPlp");
        System.out.println(idPlpMaster);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return1998516329";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#validarPostagemReversa(java.lang.String codAdministrativo, java.lang.String codigoServico, java.lang.String cepDestinatario, java.lang.String idCartaoPostagem, br.com.correios.bsb.sigep.master.bean.cliente.ColetaReversa coleta, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.Boolean validarPostagemReversa(java.lang.String codAdministrativo, java.lang.String codigoServico, java.lang.String cepDestinatario, java.lang.String idCartaoPostagem, br.com.correios.bsb.sigep.master.bean.cliente.ColetaReversa coleta, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation validarPostagemReversa");
        System.out.println(codAdministrativo);
        System.out.println(codigoServico);
        System.out.println(cepDestinatario);
        System.out.println(idCartaoPostagem);
        System.out.println(coleta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaCliente(java.lang.String idContrato, java.lang.String idCartaoPostagem, java.lang.String usuario, java.lang.String senha)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP buscaCliente(java.lang.String idContrato, java.lang.String idCartaoPostagem, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation buscaCliente");
        System.out.println(idContrato);
        System.out.println(idCartaoPostagem);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP _return = new br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP();
            _return.setCnpj("Cnpj1823191372");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _returnContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP _returnContratosVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP();
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP> _returnContratosVal1CartoesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP>();
            _returnContratosVal1.getCartoesPostagem().addAll(_returnContratosVal1CartoesPostagem);
            br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP _returnContratosVal1Cliente = new br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP();
            _returnContratosVal1Cliente.setCnpj("Cnpj1383737995");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _returnContratosVal1ClienteContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
            _returnContratosVal1Cliente.getContratos().addAll(_returnContratosVal1ClienteContratos);
            _returnContratosVal1Cliente.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.808-03:00"));
            _returnContratosVal1Cliente.setDatajAtualizacao(Integer.valueOf(1583469962));
            _returnContratosVal1Cliente.setDescricaoStatusCliente("DescricaoStatusCliente-1015697218");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta> _returnContratosVal1ClienteGerenteConta = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta>();
            _returnContratosVal1Cliente.getGerenteConta().addAll(_returnContratosVal1ClienteGerenteConta);
            _returnContratosVal1Cliente.setHorajAtualizacao(Long.valueOf(4557250759131738860l));
            _returnContratosVal1Cliente.setId(-8272237658381680556l);
            _returnContratosVal1Cliente.setInscricaoEstadual("InscricaoEstadual169668503");
            _returnContratosVal1Cliente.setNome("Nome1301644363");
            _returnContratosVal1Cliente.setStatusCodigo("StatusCodigo-905215845");
            _returnContratosVal1.setCliente(_returnContratosVal1Cliente);
            _returnContratosVal1.setCodigoCliente(-1899100631152083400l);
            _returnContratosVal1.setCodigoDiretoria("CodigoDiretoria-1210381864");
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERPPK _returnContratosVal1ContratoPK = new br.com.correios.bsb.sigep.master.bean.cliente.ContratoERPPK();
            _returnContratosVal1ContratoPK.setDiretoria(4677120300447602949l);
            _returnContratosVal1ContratoPK.setNumero("Numero-1468326393");
            _returnContratosVal1.setContratoPK(_returnContratosVal1ContratoPK);
            _returnContratosVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.808-03:00"));
            _returnContratosVal1.setDataAtualizacaoDDMMYYYY("DataAtualizacaoDDMMYYYY938866764");
            _returnContratosVal1.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.808-03:00"));
            _returnContratosVal1.setDataVigenciaFimDDMMYYYY("DataVigenciaFimDDMMYYYY1903950702");
            _returnContratosVal1.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.809-03:00"));
            _returnContratosVal1.setDataVigenciaInicioDDMMYYYY("DataVigenciaInicioDDMMYYYY-405796709");
            _returnContratosVal1.setDatajAtualizacao(Integer.valueOf(1687649658));
            _returnContratosVal1.setDatajVigenciaFim(Integer.valueOf(-1354714034));
            _returnContratosVal1.setDatajVigenciaInicio(Integer.valueOf(1824094620));
            _returnContratosVal1.setDescricaoDiretoriaRegional("DescricaoDiretoriaRegional-2074825891");
            _returnContratosVal1.setDescricaoStatus("DescricaoStatus1361188730");
            br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP _returnContratosVal1DiretoriaRegional = new br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP();
            _returnContratosVal1DiretoriaRegional.setDiretoriaRegional("DiretoriaRegional-2007549161");
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _returnContratosVal1DiretoriaRegionalEndereco = new br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP();
            _returnContratosVal1DiretoriaRegionalEndereco.setBairro("Bairro1575533968");
            _returnContratosVal1DiretoriaRegionalEndereco.setCep("Cep-1538449833");
            _returnContratosVal1DiretoriaRegionalEndereco.setCidade("Cidade244940634");
            _returnContratosVal1DiretoriaRegionalEndereco.setComplemento2("Complemento2-1749946024");
            _returnContratosVal1DiretoriaRegionalEndereco.setEnd("End-1264526074");
            _returnContratosVal1DiretoriaRegionalEndereco.setUf("Uf256838805");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _returnContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
            _returnContratosVal1DiretoriaRegionalEndereco.getUnidadesPostagem().addAll(_returnContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem);
            _returnContratosVal1DiretoriaRegional.setEndereco(_returnContratosVal1DiretoriaRegionalEndereco);
            _returnContratosVal1DiretoriaRegional.setId("Id761690116");
            _returnContratosVal1DiretoriaRegional.setNome("Nome65272922");
            _returnContratosVal1DiretoriaRegional.setStatus("Status1889174759");
            _returnContratosVal1DiretoriaRegional.setTipo("Tipo-196663575");
            _returnContratosVal1.setDiretoriaRegional(_returnContratosVal1DiretoriaRegional);
            _returnContratosVal1.setHorajAtualizacao(Integer.valueOf(764971637));
            _returnContratosVal1.setStatusCodigo("StatusCodigo-486307481");
            _returnContratos.add(_returnContratosVal1);
            _return.getContratos().addAll(_returnContratos);
            _return.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.809-03:00"));
            _return.setDatajAtualizacao(Integer.valueOf(1600796381));
            _return.setDescricaoStatusCliente("DescricaoStatusCliente-1584901141");
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta> _returnGerenteConta = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta>();
            br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta _returnGerenteContaVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.GerenteConta();
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP> _returnGerenteContaVal1ClientesVisiveis = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP>();
            _returnGerenteContaVal1.getClientesVisiveis().addAll(_returnGerenteContaVal1ClientesVisiveis);
            _returnGerenteContaVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.809-03:00"));
            _returnGerenteContaVal1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.809-03:00"));
            _returnGerenteContaVal1.setDataSenha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.809-03:00"));
            _returnGerenteContaVal1.setLogin("Login1043402602");
            _returnGerenteContaVal1.setMatricula("Matricula574924648");
            _returnGerenteContaVal1.setSenha("Senha-1272427479");
            br.com.correios.bsb.sigep.master.bean.cliente.StatusGerente _returnGerenteContaVal1Status = br.com.correios.bsb.sigep.master.bean.cliente.StatusGerente.ATIVO;
            _returnGerenteContaVal1.setStatus(_returnGerenteContaVal1Status);
            br.com.correios.bsb.sigep.master.bean.cliente.TipoGerente _returnGerenteContaVal1TipoGerente = br.com.correios.bsb.sigep.master.bean.cliente.TipoGerente.GERENTE_CONTA;
            _returnGerenteContaVal1.setTipoGerente(_returnGerenteContaVal1TipoGerente);
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UsuarioInstalacao> _returnGerenteContaVal1UsuariosInstalacao = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UsuarioInstalacao>();
            _returnGerenteContaVal1.getUsuariosInstalacao().addAll(_returnGerenteContaVal1UsuariosInstalacao);
            _returnGerenteContaVal1.setValidade("Validade37066447");
            _returnGerenteConta.add(_returnGerenteContaVal1);
            _return.getGerenteConta().addAll(_returnGerenteConta);
            _return.setHorajAtualizacao(Long.valueOf(8869225606212917024l));
            _return.setId(-6942822569211481162l);
            _return.setInscricaoEstadual("InscricaoEstadual-1800760990");
            _return.setNome("Nome-1366729966");
            _return.setStatusCodigo("StatusCodigo-1549932526");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaPagamentoEntrega(java.lang.String usuario, java.lang.String senha, java.lang.String contrato, java.lang.String dataInicio, java.lang.String dataFim, java.lang.String etiqueta)*
     */
    public java.lang.String buscaPagamentoEntrega(java.lang.String usuario, java.lang.String senha, java.lang.String contrato, java.lang.String dataInicio, java.lang.String dataFim, java.lang.String etiqueta) throws ErroMontagemRelatorio_Exception,  SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation buscaPagamentoEntrega");
        System.out.println(usuario);
        System.out.println(senha);
        System.out.println(contrato);
        System.out.println(dataInicio);
        System.out.println(dataFim);
        System.out.println(etiqueta);
        try {
            java.lang.String _return = "_return-1532076472";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ErroMontagemRelatorio_Exception("ErroMontagemRelatorio...");
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#solicitarPostagemScol(java.lang.Integer codAdministrativo, java.lang.String xml, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String solicitarPostagemScol(java.lang.Integer codAdministrativo, java.lang.String xml, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation solicitarPostagemScol");
        System.out.println(codAdministrativo);
        System.out.println(xml);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return1030347950";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaServicos(java.lang.String idContrato, java.lang.String idCartaoPostagem, java.lang.String usuario, java.lang.String senha)*
     */
    public java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> buscaServicos(java.lang.String idContrato, java.lang.String idCartaoPostagem, java.lang.String usuario, java.lang.String senha) throws SigepClienteException,  AutenticacaoException   {
        LOG.info("Executing operation buscaServicos");
        System.out.println(idContrato);
        System.out.println(idCartaoPostagem);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _return = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP>();
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP _returnVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP();
            _returnVal1.setCodigo("Codigo658454265");
            _returnVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.811-03:00"));
            _returnVal1.setDatajAtualizacao(Integer.valueOf(1082295148));
            _returnVal1.setDescricao("Descricao1269269855");
            _returnVal1.setHorajAtualizacao(Integer.valueOf(-1482625934));
            _returnVal1.setId(-2259901757514028911l);
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep _returnVal1ServicoSigep = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep();
            br.com.correios.bsb.sigep.master.bean.cliente.CategoriaServico _returnVal1ServicoSigepCategoriaServico = br.com.correios.bsb.sigep.master.bean.cliente.CategoriaServico.PAC;
            _returnVal1ServicoSigep.setCategoriaServico(_returnVal1ServicoSigepCategoriaServico);
            br.com.correios.bsb.sigep.master.bean.cliente.ChancelaMaster _returnVal1ServicoSigepChancela = new br.com.correios.bsb.sigep.master.bean.cliente.ChancelaMaster();
            br.com.correios.bsb.sigep.master.bean.cliente.SimNao _returnVal1ServicoSigepChancelaAtivo = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
            _returnVal1ServicoSigepChancela.setAtivo(_returnVal1ServicoSigepChancelaAtivo);
            byte[] _returnVal1ServicoSigepChancelaChancela = new byte[] {};
            _returnVal1ServicoSigepChancela.setChancela(_returnVal1ServicoSigepChancelaChancela);
            _returnVal1ServicoSigepChancela.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.811-03:00"));
            _returnVal1ServicoSigepChancela.setDescricao("Descricao1899740095");
            _returnVal1ServicoSigepChancela.setId(Long.valueOf(-9216501634561352287l));
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep> _returnVal1ServicoSigepChancelaServicosSigep = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep>();
            _returnVal1ServicoSigepChancela.getServicosSigep().addAll(_returnVal1ServicoSigepChancelaServicosSigep);
            _returnVal1ServicoSigep.setChancela(_returnVal1ServicoSigepChancela);
            _returnVal1ServicoSigep.setDescricao("Descricao1233384845");
            _returnVal1ServicoSigep.setExigeDimensoes(Boolean.valueOf(false));
            _returnVal1ServicoSigep.setExigeValorCobrar(Boolean.valueOf(true));
            _returnVal1ServicoSigep.setImitm(8822838927107145098l);
            _returnVal1ServicoSigep.setPagamentoEntrega("PagamentoEntrega-810696258");
            _returnVal1ServicoSigep.setRemessaAgrupada("RemessaAgrupada-652858685");
            br.com.correios.bsb.sigep.master.bean.cliente.SimNao _returnVal1ServicoSigepRestricao = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.S;
            _returnVal1ServicoSigep.setRestricao(_returnVal1ServicoSigepRestricao);
            _returnVal1ServicoSigep.setServico(6646604659116480341l);
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP _returnVal1ServicoSigepServicoERP = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP();
            _returnVal1ServicoSigepServicoERP.setCodigo("Codigo1371709073");
            _returnVal1ServicoSigepServicoERP.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.811-03:00"));
            _returnVal1ServicoSigepServicoERP.setDatajAtualizacao(Integer.valueOf(-421019992));
            _returnVal1ServicoSigepServicoERP.setDescricao("Descricao863267612");
            _returnVal1ServicoSigepServicoERP.setHorajAtualizacao(Integer.valueOf(1383855561));
            _returnVal1ServicoSigepServicoERP.setId(-7313632796526670948l);
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep _returnVal1ServicoSigepServicoERPServicoSigep = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep();
            br.com.correios.bsb.sigep.master.bean.cliente.CategoriaServico _returnVal1ServicoSigepServicoERPServicoSigepCategoriaServico = br.com.correios.bsb.sigep.master.bean.cliente.CategoriaServico.PAC;
            _returnVal1ServicoSigepServicoERPServicoSigep.setCategoriaServico(_returnVal1ServicoSigepServicoERPServicoSigepCategoriaServico);
            br.com.correios.bsb.sigep.master.bean.cliente.ChancelaMaster _returnVal1ServicoSigepServicoERPServicoSigepChancela = new br.com.correios.bsb.sigep.master.bean.cliente.ChancelaMaster();
            br.com.correios.bsb.sigep.master.bean.cliente.SimNao _returnVal1ServicoSigepServicoERPServicoSigepChancelaAtivo = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setAtivo(_returnVal1ServicoSigepServicoERPServicoSigepChancelaAtivo);
            byte[] _returnVal1ServicoSigepServicoERPServicoSigepChancelaChancela = new byte[] {};
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setChancela(_returnVal1ServicoSigepServicoERPServicoSigepChancelaChancela);
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.812-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setDescricao("Descricao1741074502");
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setId(Long.valueOf(-9022813525165685456l));
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep> _returnVal1ServicoSigepServicoERPServicoSigepChancelaServicosSigep = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoSigep>();
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.getServicosSigep().addAll(_returnVal1ServicoSigepServicoERPServicoSigepChancelaServicosSigep);
            _returnVal1ServicoSigepServicoERPServicoSigep.setChancela(_returnVal1ServicoSigepServicoERPServicoSigepChancela);
            _returnVal1ServicoSigepServicoERPServicoSigep.setDescricao("Descricao684859828");
            _returnVal1ServicoSigepServicoERPServicoSigep.setExigeDimensoes(Boolean.valueOf(true));
            _returnVal1ServicoSigepServicoERPServicoSigep.setExigeValorCobrar(Boolean.valueOf(true));
            _returnVal1ServicoSigepServicoERPServicoSigep.setImitm(-1351426739649451953l);
            _returnVal1ServicoSigepServicoERPServicoSigep.setPagamentoEntrega("PagamentoEntrega1208211503");
            _returnVal1ServicoSigepServicoERPServicoSigep.setRemessaAgrupada("RemessaAgrupada-134556116");
            br.com.correios.bsb.sigep.master.bean.cliente.SimNao _returnVal1ServicoSigepServicoERPServicoSigepRestricao = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
            _returnVal1ServicoSigepServicoERPServicoSigep.setRestricao(_returnVal1ServicoSigepServicoERPServicoSigepRestricao);
            _returnVal1ServicoSigepServicoERPServicoSigep.setServico(2620612128985001264l);
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP _returnVal1ServicoSigepServicoERPServicoSigepServicoERP = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP();
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setCodigo("Codigo2144940392");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.812-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setDatajAtualizacao(Integer.valueOf(-274038301));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setDescricao("Descricao1369377926");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setHorajAtualizacao(Integer.valueOf(1755568776));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setId(-5244105287197767523l);
                        _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setServicoSigep(null);
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP> _returnVal1ServicoSigepServicoERPServicoSigepServicoERPServicosAdicionais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP>();
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.getServicosAdicionais().addAll(_returnVal1ServicoSigepServicoERPServicoSigepServicoERPServicosAdicionais);
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo1Codigo("Tipo1Codigo929354900");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo1Descricao("Tipo1Descricao-403568438");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo2Codigo("Tipo2Codigo647617590");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo2Descricao("Tipo2Descricao1871793843");
            br.com.correios.bsb.sigep.master.bean.cliente.VigenciaERP _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia = new br.com.correios.bsb.sigep.master.bean.cliente.VigenciaERP();
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDataFinal(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.812-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDataInicial(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.812-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDatajFim(Integer.valueOf(-1530942836));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDatajIni(Integer.valueOf(-99759487));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setId(Long.valueOf(-920997203821587900l));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setVigencia(_returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia);
            _returnVal1ServicoSigepServicoERPServicoSigep.setServicoERP(_returnVal1ServicoSigepServicoERPServicoSigepServicoERP);
            _returnVal1ServicoSigepServicoERPServicoSigep.setSsiCoCodigoPostal("SsiCoCodigoPostal729665735");
            _returnVal1ServicoSigepServicoERP.setServicoSigep(_returnVal1ServicoSigepServicoERPServicoSigep);
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP> _returnVal1ServicoSigepServicoERPServicosAdicionais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP>();
            _returnVal1ServicoSigepServicoERP.getServicosAdicionais().addAll(_returnVal1ServicoSigepServicoERPServicosAdicionais);
            _returnVal1ServicoSigepServicoERP.setTipo1Codigo("Tipo1Codigo1650687074");
            _returnVal1ServicoSigepServicoERP.setTipo1Descricao("Tipo1Descricao1269150982");
            _returnVal1ServicoSigepServicoERP.setTipo2Codigo("Tipo2Codigo167194024");
            _returnVal1ServicoSigepServicoERP.setTipo2Descricao("Tipo2Descricao883922739");
            br.com.correios.bsb.sigep.master.bean.cliente.VigenciaERP _returnVal1ServicoSigepServicoERPVigencia = new br.com.correios.bsb.sigep.master.bean.cliente.VigenciaERP();
            _returnVal1ServicoSigepServicoERPVigencia.setDataFinal(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.812-03:00"));
            _returnVal1ServicoSigepServicoERPVigencia.setDataInicial(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.813-03:00"));
            _returnVal1ServicoSigepServicoERPVigencia.setDatajFim(Integer.valueOf(937260224));
            _returnVal1ServicoSigepServicoERPVigencia.setDatajIni(Integer.valueOf(-1850954830));
            _returnVal1ServicoSigepServicoERPVigencia.setId(Long.valueOf(-6130289645880264617l));
            _returnVal1ServicoSigepServicoERP.setVigencia(_returnVal1ServicoSigepServicoERPVigencia);
            _returnVal1ServicoSigep.setServicoERP(_returnVal1ServicoSigepServicoERP);
            _returnVal1ServicoSigep.setSsiCoCodigoPostal("SsiCoCodigoPostal-1971014076");
            _returnVal1.setServicoSigep(_returnVal1ServicoSigep);
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP> _returnVal1ServicosAdicionais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP>();
            br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP _returnVal1ServicosAdicionaisVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalERP();
            _returnVal1ServicosAdicionaisVal1.setCategoria("Categoria372741905");
            _returnVal1ServicosAdicionaisVal1.setCodigo("Codigo1966550849");
            _returnVal1ServicosAdicionaisVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.813-03:00"));
            _returnVal1ServicosAdicionaisVal1.setDatajAtualizacao(Integer.valueOf(2037318292));
            _returnVal1ServicosAdicionaisVal1.setDescricao("Descricao1752013276");
            _returnVal1ServicosAdicionaisVal1.setHorajAtualizacao(Integer.valueOf(397931544));
            _returnVal1ServicosAdicionaisVal1.setId(Integer.valueOf(-674002736));
            _returnVal1ServicosAdicionaisVal1.setSigla("Sigla130568621");
            br.com.correios.bsb.sigep.master.bean.cliente.ValorDeclarado _returnVal1ServicosAdicionaisVal1ValorDeclarado = new br.com.correios.bsb.sigep.master.bean.cliente.ValorDeclarado();
            _returnVal1ServicosAdicionaisVal1ValorDeclarado.setMaximo(Double.valueOf(0.6501562583920292));
            _returnVal1ServicosAdicionaisVal1ValorDeclarado.setMinimo(Double.valueOf(0.41064216715178903));
            _returnVal1ServicosAdicionaisVal1.setValorDeclarado(_returnVal1ServicosAdicionaisVal1ValorDeclarado);
            _returnVal1ServicosAdicionais.add(_returnVal1ServicosAdicionaisVal1);
            _returnVal1.getServicosAdicionais().addAll(_returnVal1ServicosAdicionais);
            _returnVal1.setTipo1Codigo("Tipo1Codigo-1669400349");
            _returnVal1.setTipo1Descricao("Tipo1Descricao91488059");
            _returnVal1.setTipo2Codigo("Tipo2Codigo-1383398148");
            _returnVal1.setTipo2Descricao("Tipo2Descricao-1864754379");
            br.com.correios.bsb.sigep.master.bean.cliente.VigenciaERP _returnVal1Vigencia = new br.com.correios.bsb.sigep.master.bean.cliente.VigenciaERP();
            _returnVal1Vigencia.setDataFinal(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.813-03:00"));
            _returnVal1Vigencia.setDataInicial(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.813-03:00"));
            _returnVal1Vigencia.setDatajFim(Integer.valueOf(-295361369));
            _returnVal1Vigencia.setDatajIni(Integer.valueOf(-1677850120));
            _returnVal1Vigencia.setId(Long.valueOf(9134945463501834543l));
            _returnVal1.setVigencia(_returnVal1Vigencia);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new AutenticacaoException("AutenticacaoException...");
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#obterMensagemParametrizada(java.lang.Short id)*
     */
    public br.com.correios.bsb.sigep.master.bean.cliente.MensagemParametrizadaTO obterMensagemParametrizada(java.lang.Short id) {
        LOG.info("Executing operation obterMensagemParametrizada");
        System.out.println(id);
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.MensagemParametrizadaTO _return = new br.com.correios.bsb.sigep.master.bean.cliente.MensagemParametrizadaTO();
            _return.setMensagem("Mensagem667298261");
            br.com.correios.bsb.sigep.master.bean.cliente.TipoMensagem _returnTipo = br.com.correios.bsb.sigep.master.bean.cliente.TipoMensagem.E;
            _return.setTipo(_returnTipo);
            _return.setTitulo("Titulo-3036909");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente#buscaOpcoes(java.util.List<java.lang.String> listaObjetos, java.lang.String tipoResultado, java.lang.String usuario, java.lang.String senha)*
     */
    public java.lang.String buscaOpcoes(java.util.List<java.lang.String> listaObjetos, java.lang.String tipoResultado, java.lang.String usuario, java.lang.String senha) throws SigepClienteException   {
        LOG.info("Executing operation buscaOpcoes");
        System.out.println(listaObjetos);
        System.out.println(tipoResultado);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return1803077602";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

}
