
package br.com.correios.bsb.sigep.master.bean.cliente;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-12-21T22:37:58.648-03:00
 * Generated source version: 3.4.4
 *
 */
public final class AtendeCliente_AtendeClientePort_Client {

    private static final QName SERVICE_NAME = new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClienteService");

    private AtendeCliente_AtendeClientePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AtendeClienteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AtendeClienteService ss = new AtendeClienteService(wsdlURL, SERVICE_NAME);
        AtendeCliente port = ss.getAtendeClientePort();

        {
        System.out.println("Invoking buscaServicosAdicionaisAtivos...");
        java.lang.String _buscaServicosAdicionaisAtivos_usuario = "_buscaServicosAdicionaisAtivos_usuario-1120449343";
        java.lang.String _buscaServicosAdicionaisAtivos_senha = "_buscaServicosAdicionaisAtivos_senha-882585366";
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML> _buscaServicosAdicionaisAtivos__return = port.buscaServicosAdicionaisAtivos(_buscaServicosAdicionaisAtivos_usuario, _buscaServicosAdicionaisAtivos_senha);
            System.out.println("buscaServicosAdicionaisAtivos.result=" + _buscaServicosAdicionaisAtivos__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking fechaPlp...");
        java.lang.String _fechaPlp_xml = "_fechaPlp_xml-1497116778";
        java.lang.Long _fechaPlp_idPlpCliente = Long.valueOf(7999508717528143770l);
        java.lang.String _fechaPlp_cartaoPostagem = "_fechaPlp_cartaoPostagem-1694892611";
        java.lang.String _fechaPlp_faixaEtiquetas = "_fechaPlp_faixaEtiquetas-113588554";
        java.lang.String _fechaPlp_usuario = "_fechaPlp_usuario-2092687716";
        java.lang.String _fechaPlp_senha = "_fechaPlp_senha469424222";
        try {
            java.lang.Long _fechaPlp__return = port.fechaPlp(_fechaPlp_xml, _fechaPlp_idPlpCliente, _fechaPlp_cartaoPostagem, _fechaPlp_faixaEtiquetas, _fechaPlp_usuario, _fechaPlp_senha);
            System.out.println("fechaPlp.result=" + _fechaPlp__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validaPlp...");
        long _validaPlp_cliente = 9031027922542945071l;
        java.lang.String _validaPlp_numero = "_validaPlp_numero607705382";
        long _validaPlp_diretoria = -435723640062427689l;
        java.lang.String _validaPlp_cartao = "_validaPlp_cartao1665245220";
        java.lang.String _validaPlp_unidadePostagem = "_validaPlp_unidadePostagem888416743";
        java.lang.Long _validaPlp_servico = Long.valueOf(4094095844533209852l);
        java.util.List<java.lang.String> _validaPlp_servicosAdicionais = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validaPlp_servicosAdicionaisVal1 = "_validaPlp_servicosAdicionaisVal1176378873";
        _validaPlp_servicosAdicionais.add(_validaPlp_servicosAdicionaisVal1);
        java.lang.String _validaPlp_usuario = "_validaPlp_usuario-685181168";
        java.lang.String _validaPlp_senha = "_validaPlp_senha2086044807";
        try {
            boolean _validaPlp__return = port.validaPlp(_validaPlp_cliente, _validaPlp_numero, _validaPlp_diretoria, _validaPlp_cartao, _validaPlp_unidadePostagem, _validaPlp_servico, _validaPlp_servicosAdicionais, _validaPlp_usuario, _validaPlp_senha);
            System.out.println("validaPlp.result=" + _validaPlp__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking calculaTarifaServico...");
        java.lang.String _calculaTarifaServico_codAdministrativo = "_calculaTarifaServico_codAdministrativo-598184908";
        java.lang.String _calculaTarifaServico_usuario = "_calculaTarifaServico_usuario731188281";
        java.lang.String _calculaTarifaServico_senha = "_calculaTarifaServico_senha21067677";
        java.lang.String _calculaTarifaServico_codServico = "_calculaTarifaServico_codServico-336492886";
        java.lang.String _calculaTarifaServico_cepOrigem = "_calculaTarifaServico_cepOrigem-446448317";
        java.lang.String _calculaTarifaServico_cepDestino = "_calculaTarifaServico_cepDestino40521146";
        java.lang.String _calculaTarifaServico_peso = "_calculaTarifaServico_peso2485926";
        java.lang.Integer _calculaTarifaServico_codFormato = Integer.valueOf(-1978398280);
        java.lang.Double _calculaTarifaServico_comprimento = Double.valueOf(0.1523736931365488);
        java.lang.Double _calculaTarifaServico_altura = Double.valueOf(0.07573364778408853);
        java.lang.Double _calculaTarifaServico_largura = Double.valueOf(0.8549373779179976);
        java.lang.Double _calculaTarifaServico_diametro = Double.valueOf(0.8331056701226096);
        java.lang.String _calculaTarifaServico_codMaoPropria = "_calculaTarifaServico_codMaoPropria-1776391165";
        java.lang.Double _calculaTarifaServico_valorDeclarado = Double.valueOf(0.3696599884702466);
        java.lang.String _calculaTarifaServico_codAvisoRecebimento = "_calculaTarifaServico_codAvisoRecebimento-1196465901";
        try {
            java.lang.String _calculaTarifaServico__return = port.calculaTarifaServico(_calculaTarifaServico_codAdministrativo, _calculaTarifaServico_usuario, _calculaTarifaServico_senha, _calculaTarifaServico_codServico, _calculaTarifaServico_cepOrigem, _calculaTarifaServico_cepDestino, _calculaTarifaServico_peso, _calculaTarifaServico_codFormato, _calculaTarifaServico_comprimento, _calculaTarifaServico_altura, _calculaTarifaServico_largura, _calculaTarifaServico_diametro, _calculaTarifaServico_codMaoPropria, _calculaTarifaServico_valorDeclarado, _calculaTarifaServico_codAvisoRecebimento);
            System.out.println("calculaTarifaServico.result=" + _calculaTarifaServico__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking verificaSeTodosObjetosCancelados...");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _verificaSeTodosObjetosCancelados_arg0 = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal _verificaSeTodosObjetosCancelados_arg0Val1 = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal();
        _verificaSeTodosObjetosCancelados_arg0Val1.setCodigoEtiqueta("CodigoEtiqueta1070962184");
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.718-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataBloqueioObjeto(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.720-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataCancelamentoEtiqueta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.720-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.720-03:00"));
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK _verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK();
        _verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK.setCodigoEtiqueta("CodigoEtiqueta154793198");
        _verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK.setPlpNu(-4106081203869676042l);
        _verificaSeTodosObjetosCancelados_arg0Val1.setObjetoPostalPK(_verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK);
        _verificaSeTodosObjetosCancelados_arg0Val1.setPlpNu(Long.valueOf(3755941582944745901l));
        br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem();
        br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setCodigoAdministrativo("CodigoAdministrativo1348127039");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.getContratos().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemContratos);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.720-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.721-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.721-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDatajAtualizacao(Integer.valueOf(-499350140));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaFim(Integer.valueOf(-1339231457));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaInicio(Integer.valueOf(856185634));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoStatusCartao("DescricaoStatusCartao-620165908");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica1899428957");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setHorajAtualizacao(Integer.valueOf(2015137853));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setNumero("Numero-1615774694");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemServicos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.getServicos().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemServicos);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setStatusCartaoPostagem("StatusCartaoPostagem1528417795");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setStatusCodigo("StatusCodigo-1055229582");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setUnidadeGenerica("UnidadeGenerica-1430994496");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.getUnidadesPostagem().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setCartaoPostagem(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemConteudoProibido = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.S;
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setConteudoProibido(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemConteudoProibido);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.721-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataAtualizacaoSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.721-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataFechamento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.721-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataPostagem(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.721-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataPostagemSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.722-03:00"));
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemObjetosPostais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.getObjetosPostais().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemObjetosPostais);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setPlpCliente(-98342157911571765l);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setPlpNu(1690598306497660735l);
        java.util.List<java.lang.Integer> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXml = new java.util.ArrayList<java.lang.Integer>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.getPlpXml().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXml);
        java.util.List<java.lang.Integer> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXmlRetorno = new java.util.ArrayList<java.lang.Integer>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.getPlpXmlRetorno().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXmlRetorno);
        br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemStatus = br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp.ABERTA;
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setStatus(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemStatus);
        _verificaSeTodosObjetosCancelados_arg0Val1.setPreListaPostagem(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _verificaSeTodosObjetosCancelados_arg0Val1RestricaoAerea = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.S;
        _verificaSeTodosObjetosCancelados_arg0Val1.setRestricaoAerea(_verificaSeTodosObjetosCancelados_arg0Val1RestricaoAerea);
        _verificaSeTodosObjetosCancelados_arg0Val1.setStatusBloqueio("StatusBloqueio214078458");
        br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal _verificaSeTodosObjetosCancelados_arg0Val1StatusEtiqueta = br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal.CANCELADO;
        _verificaSeTodosObjetosCancelados_arg0Val1.setStatusEtiqueta(_verificaSeTodosObjetosCancelados_arg0Val1StatusEtiqueta);
        _verificaSeTodosObjetosCancelados_arg0.add(_verificaSeTodosObjetosCancelados_arg0Val1);
        try {
            boolean _verificaSeTodosObjetosCancelados__return = port.verificaSeTodosObjetosCancelados(_verificaSeTodosObjetosCancelados_arg0);
            System.out.println("verificaSeTodosObjetosCancelados.result=" + _verificaSeTodosObjetosCancelados__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking cancelarObjeto...");
        java.lang.Long _cancelarObjeto_idPlp = Long.valueOf(6888971819358230552l);
        java.lang.String _cancelarObjeto_numeroEtiqueta = "_cancelarObjeto_numeroEtiqueta1290951479";
        java.lang.String _cancelarObjeto_usuario = "_cancelarObjeto_usuario1612808345";
        java.lang.String _cancelarObjeto_senha = "_cancelarObjeto_senha1602467810";
        try {
            java.lang.Boolean _cancelarObjeto__return = port.cancelarObjeto(_cancelarObjeto_idPlp, _cancelarObjeto_numeroEtiqueta, _cancelarObjeto_usuario, _cancelarObjeto_senha);
            System.out.println("cancelarObjeto.result=" + _cancelarObjeto__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking pesquisarParametrosPorDescricao...");
        java.lang.String _pesquisarParametrosPorDescricao_prefix = "_pesquisarParametrosPorDescricao_prefix1075120609";
        br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO _pesquisarParametrosPorDescricao__return = port.pesquisarParametrosPorDescricao(_pesquisarParametrosPorDescricao_prefix);
        System.out.println("pesquisarParametrosPorDescricao.result=" + _pesquisarParametrosPorDescricao__return);


        }
        {
        System.out.println("Invoking atualizaPagamentoNaEntrega...");
        java.lang.String _atualizaPagamentoNaEntrega_usuario = "_atualizaPagamentoNaEntrega_usuario-1248693489";
        java.lang.String _atualizaPagamentoNaEntrega_senha = "_atualizaPagamentoNaEntrega_senha-650990699";
        try {
            java.lang.String _atualizaPagamentoNaEntrega__return = port.atualizaPagamentoNaEntrega(_atualizaPagamentoNaEntrega_usuario, _atualizaPagamentoNaEntrega_senha);
            System.out.println("atualizaPagamentoNaEntrega.result=" + _atualizaPagamentoNaEntrega__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking obterClienteAtualizacao...");
        java.lang.String _obterClienteAtualizacao_cnpjCliente = "_obterClienteAtualizacao_cnpjCliente929641118";
        java.lang.String _obterClienteAtualizacao_usuario = "_obterClienteAtualizacao_usuario39340767";
        java.lang.String _obterClienteAtualizacao_senha = "_obterClienteAtualizacao_senha-1563372013";
        try {
            javax.xml.datatype.XMLGregorianCalendar _obterClienteAtualizacao__return = port.obterClienteAtualizacao(_obterClienteAtualizacao_cnpjCliente, _obterClienteAtualizacao_usuario, _obterClienteAtualizacao_senha);
            System.out.println("obterClienteAtualizacao.result=" + _obterClienteAtualizacao__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking verificaDisponibilidadeServico...");
        java.lang.Integer _verificaDisponibilidadeServico_codAdministrativo = Integer.valueOf(-106892026);
        java.lang.String _verificaDisponibilidadeServico_numeroServico = "_verificaDisponibilidadeServico_numeroServico1040969668";
        java.lang.String _verificaDisponibilidadeServico_cepOrigem = "_verificaDisponibilidadeServico_cepOrigem-2080642888";
        java.lang.String _verificaDisponibilidadeServico_cepDestino = "_verificaDisponibilidadeServico_cepDestino1839403511";
        java.lang.String _verificaDisponibilidadeServico_usuario = "_verificaDisponibilidadeServico_usuario435682452";
        java.lang.String _verificaDisponibilidadeServico_senha = "_verificaDisponibilidadeServico_senha973053307";
        try {
            java.lang.String _verificaDisponibilidadeServico__return = port.verificaDisponibilidadeServico(_verificaDisponibilidadeServico_codAdministrativo, _verificaDisponibilidadeServico_numeroServico, _verificaDisponibilidadeServico_cepOrigem, _verificaDisponibilidadeServico_cepDestino, _verificaDisponibilidadeServico_usuario, _verificaDisponibilidadeServico_senha);
            System.out.println("verificaDisponibilidadeServico.result=" + _verificaDisponibilidadeServico__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking fechaPlpVariosServicos...");
        java.lang.String _fechaPlpVariosServicos_xml = "_fechaPlpVariosServicos_xml2098099711";
        java.lang.Long _fechaPlpVariosServicos_idPlpCliente = Long.valueOf(-5428932634737303219l);
        java.lang.String _fechaPlpVariosServicos_cartaoPostagem = "_fechaPlpVariosServicos_cartaoPostagem1220494832";
        java.util.List<java.lang.String> _fechaPlpVariosServicos_listaEtiquetas = new java.util.ArrayList<java.lang.String>();
        java.lang.String _fechaPlpVariosServicos_listaEtiquetasVal1 = "_fechaPlpVariosServicos_listaEtiquetasVal-1596455752";
        _fechaPlpVariosServicos_listaEtiquetas.add(_fechaPlpVariosServicos_listaEtiquetasVal1);
        java.lang.String _fechaPlpVariosServicos_usuario = "_fechaPlpVariosServicos_usuario-915025956";
        java.lang.String _fechaPlpVariosServicos_senha = "_fechaPlpVariosServicos_senha-1510118966";
        try {
            java.lang.Long _fechaPlpVariosServicos__return = port.fechaPlpVariosServicos(_fechaPlpVariosServicos_xml, _fechaPlpVariosServicos_idPlpCliente, _fechaPlpVariosServicos_cartaoPostagem, _fechaPlpVariosServicos_listaEtiquetas, _fechaPlpVariosServicos_usuario, _fechaPlpVariosServicos_senha);
            System.out.println("fechaPlpVariosServicos.result=" + _fechaPlpVariosServicos__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking geraDigitoVerificadorEtiquetas...");
        java.util.List<java.lang.String> _geraDigitoVerificadorEtiquetas_etiquetas = new java.util.ArrayList<java.lang.String>();
        java.lang.String _geraDigitoVerificadorEtiquetas_etiquetasVal1 = "_geraDigitoVerificadorEtiquetas_etiquetasVal111247024";
        _geraDigitoVerificadorEtiquetas_etiquetas.add(_geraDigitoVerificadorEtiquetas_etiquetasVal1);
        java.lang.String _geraDigitoVerificadorEtiquetas_usuario = "_geraDigitoVerificadorEtiquetas_usuario2093466907";
        java.lang.String _geraDigitoVerificadorEtiquetas_senha = "_geraDigitoVerificadorEtiquetas_senha1830102986";
        try {
            java.util.List<java.lang.Integer> _geraDigitoVerificadorEtiquetas__return = port.geraDigitoVerificadorEtiquetas(_geraDigitoVerificadorEtiquetas_etiquetas, _geraDigitoVerificadorEtiquetas_usuario, _geraDigitoVerificadorEtiquetas_senha);
            System.out.println("geraDigitoVerificadorEtiquetas.result=" + _geraDigitoVerificadorEtiquetas__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking obterEmbalagemLRS...");
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster> _obterEmbalagemLRS__return = port.obterEmbalagemLRS();
            System.out.println("obterEmbalagemLRS.result=" + _obterEmbalagemLRS__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validaEtiquetaPLP...");
        java.lang.String _validaEtiquetaPLP_numeroEtiqueta = "_validaEtiquetaPLP_numeroEtiqueta1246186132";
        java.lang.Long _validaEtiquetaPLP_idPlp = Long.valueOf(148540966550523032l);
        java.lang.String _validaEtiquetaPLP_usuario = "_validaEtiquetaPLP_usuario-2107864420";
        java.lang.String _validaEtiquetaPLP_senha = "_validaEtiquetaPLP_senha-1435504957";
        try {
            boolean _validaEtiquetaPLP__return = port.validaEtiquetaPLP(_validaEtiquetaPLP_numeroEtiqueta, _validaEtiquetaPLP_idPlp, _validaEtiquetaPLP_usuario, _validaEtiquetaPLP_senha);
            System.out.println("validaEtiquetaPLP.result=" + _validaEtiquetaPLP__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaServicosValorDeclarado...");
        java.lang.String _buscaServicosValorDeclarado_usuario = "_buscaServicosValorDeclarado_usuario-1903589171";
        java.lang.String _buscaServicosValorDeclarado_senha = "_buscaServicosValorDeclarado_senha-1122580197";
        try {
            java.util.List<java.lang.String> _buscaServicosValorDeclarado__return = port.buscaServicosValorDeclarado(_buscaServicosValorDeclarado_usuario, _buscaServicosValorDeclarado_senha);
            System.out.println("buscaServicosValorDeclarado.result=" + _buscaServicosValorDeclarado__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking consultaCEP...");
        java.lang.String _consultaCEP_cep = "_consultaCEP_cep-92308733";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _consultaCEP__return = port.consultaCEP(_consultaCEP_cep);
            System.out.println("consultaCEP.result=" + _consultaCEP__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking integrarUsuarioScol...");
        java.lang.Integer _integrarUsuarioScol_codAdministrativo = Integer.valueOf(1938417384);
        java.lang.String _integrarUsuarioScol_usuario = "_integrarUsuarioScol_usuario-1959399031";
        java.lang.String _integrarUsuarioScol_senha = "_integrarUsuarioScol_senha-1089362799";
        try {
            java.lang.Boolean _integrarUsuarioScol__return = port.integrarUsuarioScol(_integrarUsuarioScol_codAdministrativo, _integrarUsuarioScol_usuario, _integrarUsuarioScol_senha);
            System.out.println("integrarUsuarioScol.result=" + _integrarUsuarioScol__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking pesquisarDimensoesServico...");
        java.lang.String _pesquisarDimensoesServico_codigo = "_pesquisarDimensoesServico_codigo-1421917877";
        java.lang.String _pesquisarDimensoesServico_embalagem = "_pesquisarDimensoesServico_embalagem254632492";
        br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO _pesquisarDimensoesServico__return = port.pesquisarDimensoesServico(_pesquisarDimensoesServico_codigo, _pesquisarDimensoesServico_embalagem);
        System.out.println("pesquisarDimensoesServico.result=" + _pesquisarDimensoesServico__return);


        }
        {
        System.out.println("Invoking pesquisarEmbalagensPorServico...");
        java.lang.String _pesquisarEmbalagensPorServico_codigo = "_pesquisarEmbalagensPorServico_codigo1649546422";
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem> _pesquisarEmbalagensPorServico__return = port.pesquisarEmbalagensPorServico(_pesquisarEmbalagensPorServico_codigo);
        System.out.println("pesquisarEmbalagensPorServico.result=" + _pesquisarEmbalagensPorServico__return);


        }
        {
        System.out.println("Invoking atualizaRemessaAgrupada...");
        java.lang.String _atualizaRemessaAgrupada_usuario = "_atualizaRemessaAgrupada_usuario-232301399";
        java.lang.String _atualizaRemessaAgrupada_senha = "_atualizaRemessaAgrupada_senha361423311";
        try {
            java.lang.String _atualizaRemessaAgrupada__return = port.atualizaRemessaAgrupada(_atualizaRemessaAgrupada_usuario, _atualizaRemessaAgrupada_senha);
            System.out.println("atualizaRemessaAgrupada.result=" + _atualizaRemessaAgrupada__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitaPLP...");
        java.lang.Long _solicitaPLP_idPlpMaster = Long.valueOf(-5192556118442914209l);
        java.lang.String _solicitaPLP_numEtiqueta = "_solicitaPLP_numEtiqueta249729758";
        java.lang.String _solicitaPLP_usuario = "_solicitaPLP_usuario981698222";
        java.lang.String _solicitaPLP_senha = "_solicitaPLP_senha-1389414824";
        try {
            java.lang.String _solicitaPLP__return = port.solicitaPLP(_solicitaPLP_idPlpMaster, _solicitaPLP_numEtiqueta, _solicitaPLP_usuario, _solicitaPLP_senha);
            System.out.println("solicitaPLP.result=" + _solicitaPLP__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getStatusCartaoPostagem...");
        java.lang.String _getStatusCartaoPostagem_numeroCartaoPostagem = "_getStatusCartaoPostagem_numeroCartaoPostagem1012668451";
        java.lang.String _getStatusCartaoPostagem_usuario = "_getStatusCartaoPostagem_usuario1980537013";
        java.lang.String _getStatusCartaoPostagem_senha = "_getStatusCartaoPostagem_senha988893374";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.StatusCartao _getStatusCartaoPostagem__return = port.getStatusCartaoPostagem(_getStatusCartaoPostagem_numeroCartaoPostagem, _getStatusCartaoPostagem_usuario, _getStatusCartaoPostagem_senha);
            System.out.println("getStatusCartaoPostagem.result=" + _getStatusCartaoPostagem__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking verificaModalTransporte...");
        java.lang.String _verificaModalTransporte_codigoServico = "_verificaModalTransporte_codigoServico1148528730";
        java.lang.String _verificaModalTransporte_cepOrigem = "_verificaModalTransporte_cepOrigem1724269900";
        java.lang.String _verificaModalTransporte_cepDestino = "_verificaModalTransporte_cepDestino-1412957117";
        java.lang.String _verificaModalTransporte_usuario = "_verificaModalTransporte_usuario-1652571200";
        java.lang.String _verificaModalTransporte_senha = "_verificaModalTransporte_senha-228800068";
        try {
            java.lang.String _verificaModalTransporte__return = port.verificaModalTransporte(_verificaModalTransporte_codigoServico, _verificaModalTransporte_cepOrigem, _verificaModalTransporte_cepDestino, _verificaModalTransporte_usuario, _verificaModalTransporte_senha);
            System.out.println("verificaModalTransporte.result=" + _verificaModalTransporte__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaDataAtual...");
        javax.xml.datatype.XMLGregorianCalendar _buscaDataAtual__return = port.buscaDataAtual();
        System.out.println("buscaDataAtual.result=" + _buscaDataAtual__return);


        }
        {
        System.out.println("Invoking buscaTarifaVale...");
        java.lang.String _buscaTarifaVale_codAdministrativo = "_buscaTarifaVale_codAdministrativo-340890593";
        java.lang.String _buscaTarifaVale_usuario = "_buscaTarifaVale_usuario-517416718";
        java.lang.String _buscaTarifaVale_senha = "_buscaTarifaVale_senha702038485";
        java.lang.String _buscaTarifaVale_codServico = "_buscaTarifaVale_codServico-961480059";
        java.lang.String _buscaTarifaVale_cepOrigem = "_buscaTarifaVale_cepOrigem1797165173";
        java.lang.String _buscaTarifaVale_cepDestino = "_buscaTarifaVale_cepDestino-1694830461";
        java.lang.String _buscaTarifaVale_peso = "_buscaTarifaVale_peso1831094832";
        java.lang.Integer _buscaTarifaVale_codFormato = Integer.valueOf(-1037613197);
        java.lang.Double _buscaTarifaVale_comprimento = Double.valueOf(0.9688627487561947);
        java.lang.Double _buscaTarifaVale_altura = Double.valueOf(0.3082341592243789);
        java.lang.Double _buscaTarifaVale_largura = Double.valueOf(0.4967449409886119);
        java.lang.Double _buscaTarifaVale_valorDeclarado = Double.valueOf(0.9014314886046787);
        java.lang.String _buscaTarifaVale_servicoAdicional = "_buscaTarifaVale_servicoAdicional-182799977";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ValePostal _buscaTarifaVale__return = port.buscaTarifaVale(_buscaTarifaVale_codAdministrativo, _buscaTarifaVale_usuario, _buscaTarifaVale_senha, _buscaTarifaVale_codServico, _buscaTarifaVale_cepOrigem, _buscaTarifaVale_cepDestino, _buscaTarifaVale_peso, _buscaTarifaVale_codFormato, _buscaTarifaVale_comprimento, _buscaTarifaVale_altura, _buscaTarifaVale_largura, _buscaTarifaVale_valorDeclarado, _buscaTarifaVale_servicoAdicional);
            System.out.println("buscaTarifaVale.result=" + _buscaTarifaVale__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validarPostagemSimultanea...");
        java.lang.Integer _validarPostagemSimultanea_codAdministrativo = Integer.valueOf(-1810715234);
        java.lang.Integer _validarPostagemSimultanea_codigoServico = Integer.valueOf(-1011721005);
        java.lang.String _validarPostagemSimultanea_idCartaoPostagem = "_validarPostagemSimultanea_idCartaoPostagem-514636981";
        java.lang.String _validarPostagemSimultanea_cepDestinatario = "_validarPostagemSimultanea_cepDestinatario-845600265";
        br.com.correios.bsb.sigep.master.bean.cliente.ColetaSimultanea _validarPostagemSimultanea_coleta = new br.com.correios.bsb.sigep.master.bean.cliente.ColetaSimultanea();
        _validarPostagemSimultanea_coleta.setCklist("Cklist29674176");
        _validarPostagemSimultanea_coleta.setDescricao("Descricao2133337194");
        java.util.List<java.lang.String> _validarPostagemSimultanea_coletaDocumento = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validarPostagemSimultanea_coletaDocumentoVal1 = "_validarPostagemSimultanea_coletaDocumentoVal1736630389";
        _validarPostagemSimultanea_coletaDocumento.add(_validarPostagemSimultanea_coletaDocumentoVal1);
        _validarPostagemSimultanea_coleta.getDocumento().addAll(_validarPostagemSimultanea_coletaDocumento);
        _validarPostagemSimultanea_coleta.setIdCliente("IdCliente-2143969202");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.Produto> _validarPostagemSimultanea_coletaProduto = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.Produto>();
        br.com.correios.bsb.sigep.master.bean.cliente.Produto _validarPostagemSimultanea_coletaProdutoVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.Produto();
        _validarPostagemSimultanea_coletaProdutoVal1.setCodigo("Codigo-1326559289");
        _validarPostagemSimultanea_coletaProdutoVal1.setQtd("Qtd824816774");
        _validarPostagemSimultanea_coletaProdutoVal1.setTipo("Tipo-2082561590");
        _validarPostagemSimultanea_coletaProduto.add(_validarPostagemSimultanea_coletaProdutoVal1);
        _validarPostagemSimultanea_coleta.getProduto().addAll(_validarPostagemSimultanea_coletaProduto);
        br.com.correios.bsb.sigep.master.bean.cliente.Remetente _validarPostagemSimultanea_coletaRemetente = new br.com.correios.bsb.sigep.master.bean.cliente.Remetente();
        _validarPostagemSimultanea_coletaRemetente.setBairro("Bairro-1682684417");
        _validarPostagemSimultanea_coletaRemetente.setCep("Cep-2044348453");
        _validarPostagemSimultanea_coletaRemetente.setCidade("Cidade-1051415148");
        _validarPostagemSimultanea_coletaRemetente.setComplemento("Complemento1351620009");
        _validarPostagemSimultanea_coletaRemetente.setDdd("Ddd1354995467");
        _validarPostagemSimultanea_coletaRemetente.setEmail("Email1011059350");
        _validarPostagemSimultanea_coletaRemetente.setLogradouro("Logradouro859926269");
        _validarPostagemSimultanea_coletaRemetente.setNome("Nome-974360421");
        _validarPostagemSimultanea_coletaRemetente.setNumero("Numero773349027");
        _validarPostagemSimultanea_coletaRemetente.setReferencia("Referencia954025742");
        _validarPostagemSimultanea_coletaRemetente.setTelefone("Telefone-1381056545");
        _validarPostagemSimultanea_coletaRemetente.setUf("Uf-1618142720");
        _validarPostagemSimultanea_coletaRemetente.setCelular("Celular-1720913667");
        _validarPostagemSimultanea_coletaRemetente.setDddCelular("DddCelular-2041218286");
        _validarPostagemSimultanea_coletaRemetente.setIdentificacao("Identificacao-755839234");
        _validarPostagemSimultanea_coletaRemetente.setSms("Sms391241450");
        _validarPostagemSimultanea_coleta.setRemetente(_validarPostagemSimultanea_coletaRemetente);
        _validarPostagemSimultanea_coleta.setTipo("Tipo190426731");
        _validarPostagemSimultanea_coleta.setValorDeclarado("ValorDeclarado54495922");
        _validarPostagemSimultanea_coleta.setObj("Obj-110641668");
        _validarPostagemSimultanea_coleta.setObs("Obs-593957048");
        java.lang.String _validarPostagemSimultanea_usuario = "_validarPostagemSimultanea_usuario885662632";
        java.lang.String _validarPostagemSimultanea_senha = "_validarPostagemSimultanea_senha901377028";
        try {
            java.lang.Boolean _validarPostagemSimultanea__return = port.validarPostagemSimultanea(_validarPostagemSimultanea_codAdministrativo, _validarPostagemSimultanea_codigoServico, _validarPostagemSimultanea_idCartaoPostagem, _validarPostagemSimultanea_cepDestinatario, _validarPostagemSimultanea_coleta, _validarPostagemSimultanea_usuario, _validarPostagemSimultanea_senha);
            System.out.println("validarPostagemSimultanea.result=" + _validarPostagemSimultanea__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getStatusPLP...");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _getStatusPLP_arg0 = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal _getStatusPLP_arg0Val1 = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal();
        _getStatusPLP_arg0Val1.setCodigoEtiqueta("CodigoEtiqueta1262037960");
        _getStatusPLP_arg0Val1.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.744-03:00"));
        _getStatusPLP_arg0Val1.setDataBloqueioObjeto(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.744-03:00"));
        _getStatusPLP_arg0Val1.setDataCancelamentoEtiqueta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.744-03:00"));
        _getStatusPLP_arg0Val1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.745-03:00"));
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK _getStatusPLP_arg0Val1ObjetoPostalPK = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK();
        _getStatusPLP_arg0Val1ObjetoPostalPK.setCodigoEtiqueta("CodigoEtiqueta-2078865082");
        _getStatusPLP_arg0Val1ObjetoPostalPK.setPlpNu(-8272167531636466907l);
        _getStatusPLP_arg0Val1.setObjetoPostalPK(_getStatusPLP_arg0Val1ObjetoPostalPK);
        _getStatusPLP_arg0Val1.setPlpNu(Long.valueOf(-2208045486680803596l));
        br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem _getStatusPLP_arg0Val1PreListaPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem();
        br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setCodigoAdministrativo("CodigoAdministrativo-1109052060");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getContratos().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemContratos);
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.745-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.745-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.745-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajAtualizacao(Integer.valueOf(1156565630));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaFim(Integer.valueOf(-1798534262));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaInicio(Integer.valueOf(1203356197));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoStatusCartao("DescricaoStatusCartao1780078066");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica-1461972152");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setHorajAtualizacao(Integer.valueOf(-1094069888));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setNumero("Numero-1870576999");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemServicos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getServicos().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemServicos);
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setStatusCartaoPostagem("StatusCartaoPostagem-1039957029");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setStatusCodigo("StatusCodigo2074061393");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setUnidadeGenerica("UnidadeGenerica598019561");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getUnidadesPostagem().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem);
        _getStatusPLP_arg0Val1PreListaPostagem.setCartaoPostagem(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _getStatusPLP_arg0Val1PreListaPostagemConteudoProibido = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
        _getStatusPLP_arg0Val1PreListaPostagem.setConteudoProibido(_getStatusPLP_arg0Val1PreListaPostagemConteudoProibido);
        _getStatusPLP_arg0Val1PreListaPostagem.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.746-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataAtualizacaoSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.746-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataFechamento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.746-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataPostagem(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.746-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataPostagemSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2022-12-21T22:37:58.746-03:00"));
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _getStatusPLP_arg0Val1PreListaPostagemObjetosPostais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        _getStatusPLP_arg0Val1PreListaPostagem.getObjetosPostais().addAll(_getStatusPLP_arg0Val1PreListaPostagemObjetosPostais);
        _getStatusPLP_arg0Val1PreListaPostagem.setPlpCliente(-9058279635192849153l);
        _getStatusPLP_arg0Val1PreListaPostagem.setPlpNu(3429082981625623666l);
        java.util.List<java.lang.Integer> _getStatusPLP_arg0Val1PreListaPostagemPlpXml = new java.util.ArrayList<java.lang.Integer>();
        _getStatusPLP_arg0Val1PreListaPostagem.getPlpXml().addAll(_getStatusPLP_arg0Val1PreListaPostagemPlpXml);
        java.util.List<java.lang.Integer> _getStatusPLP_arg0Val1PreListaPostagemPlpXmlRetorno = new java.util.ArrayList<java.lang.Integer>();
        _getStatusPLP_arg0Val1PreListaPostagem.getPlpXmlRetorno().addAll(_getStatusPLP_arg0Val1PreListaPostagemPlpXmlRetorno);
        br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _getStatusPLP_arg0Val1PreListaPostagemStatus = br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp.FECHADA;
        _getStatusPLP_arg0Val1PreListaPostagem.setStatus(_getStatusPLP_arg0Val1PreListaPostagemStatus);
        _getStatusPLP_arg0Val1.setPreListaPostagem(_getStatusPLP_arg0Val1PreListaPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _getStatusPLP_arg0Val1RestricaoAerea = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
        _getStatusPLP_arg0Val1.setRestricaoAerea(_getStatusPLP_arg0Val1RestricaoAerea);
        _getStatusPLP_arg0Val1.setStatusBloqueio("StatusBloqueio-661576066");
        br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal _getStatusPLP_arg0Val1StatusEtiqueta = br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal.EM_BRANCO;
        _getStatusPLP_arg0Val1.setStatusEtiqueta(_getStatusPLP_arg0Val1StatusEtiqueta);
        _getStatusPLP_arg0.add(_getStatusPLP_arg0Val1);
        java.lang.String _getStatusPLP_arg1 = "_getStatusPLP_arg1-994914956";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _getStatusPLP__return = port.getStatusPLP(_getStatusPLP_arg0, _getStatusPLP_arg1);
            System.out.println("getStatusPLP.result=" + _getStatusPLP__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking pesquisarServicosAdicionais...");
        java.lang.String _pesquisarServicosAdicionais_codigo = "_pesquisarServicosAdicionais_codigo-657781323";
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO> _pesquisarServicosAdicionais__return = port.pesquisarServicosAdicionais(_pesquisarServicosAdicionais_codigo);
        System.out.println("pesquisarServicosAdicionais.result=" + _pesquisarServicosAdicionais__return);


        }
        {
        System.out.println("Invoking buscaServicosXServicosAdicionais...");
        java.lang.String _buscaServicosXServicosAdicionais_usuario = "_buscaServicosXServicosAdicionais_usuario1861776579";
        java.lang.String _buscaServicosXServicosAdicionais_senha = "_buscaServicosXServicosAdicionais_senha-986304547";
        try {
            java.util.List<java.lang.String> _buscaServicosXServicosAdicionais__return = port.buscaServicosXServicosAdicionais(_buscaServicosXServicosAdicionais_usuario, _buscaServicosXServicosAdicionais_senha);
            System.out.println("buscaServicosXServicosAdicionais.result=" + _buscaServicosXServicosAdicionais__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking cancelarPedidoScol...");
        java.lang.String _cancelarPedidoScol_codAdministrativo = "_cancelarPedidoScol_codAdministrativo-95626927";
        java.lang.String _cancelarPedidoScol_idPostagem = "_cancelarPedidoScol_idPostagem-1764128219";
        java.lang.String _cancelarPedidoScol_tipo = "_cancelarPedidoScol_tipo1751689046";
        java.lang.String _cancelarPedidoScol_usuario = "_cancelarPedidoScol_usuario469587762";
        java.lang.String _cancelarPedidoScol_senha = "_cancelarPedidoScol_senha1900564415";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.RetornoCancelamento _cancelarPedidoScol__return = port.cancelarPedidoScol(_cancelarPedidoScol_codAdministrativo, _cancelarPedidoScol_idPostagem, _cancelarPedidoScol_tipo, _cancelarPedidoScol_usuario, _cancelarPedidoScol_senha);
            System.out.println("cancelarPedidoScol.result=" + _cancelarPedidoScol__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking bloquearObjeto...");
        java.lang.String _bloquearObjeto_numeroEtiqueta = "_bloquearObjeto_numeroEtiqueta1723732693";
        java.lang.Long _bloquearObjeto_idPlp = Long.valueOf(7981130143097428444l);
        br.com.correios.bsb.sigep.master.bean.cliente.TipoBloqueio _bloquearObjeto_tipoBloqueio = br.com.correios.bsb.sigep.master.bean.cliente.TipoBloqueio.FRAUDE_BLOQUEIO;
        br.com.correios.bsb.sigep.master.bean.cliente.Acao _bloquearObjeto_acao = br.com.correios.bsb.sigep.master.bean.cliente.Acao.DEVOLVIDO_AO_REMETENTE;
        java.lang.String _bloquearObjeto_usuario = "_bloquearObjeto_usuario1638308720";
        java.lang.String _bloquearObjeto_senha = "_bloquearObjeto_senha-1498701326";
        try {
            java.lang.String _bloquearObjeto__return = port.bloquearObjeto(_bloquearObjeto_numeroEtiqueta, _bloquearObjeto_idPlp, _bloquearObjeto_tipoBloqueio, _bloquearObjeto_acao, _bloquearObjeto_usuario, _bloquearObjeto_senha);
            System.out.println("bloquearObjeto.result=" + _bloquearObjeto__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaContrato...");
        java.lang.String _buscaContrato_numero = "_buscaContrato_numero1470928653";
        long _buscaContrato_diretoria = -6658732224022468693l;
        java.lang.String _buscaContrato_usuario = "_buscaContrato_usuario-425629291";
        java.lang.String _buscaContrato_senha = "_buscaContrato_senha863177464";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP _buscaContrato__return = port.buscaContrato(_buscaContrato_numero, _buscaContrato_diretoria, _buscaContrato_usuario, _buscaContrato_senha);
            System.out.println("buscaContrato.result=" + _buscaContrato__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitaEtiquetas...");
        java.lang.String _solicitaEtiquetas_tipoDestinatario = "_solicitaEtiquetas_tipoDestinatario-1885680534";
        java.lang.String _solicitaEtiquetas_identificador = "_solicitaEtiquetas_identificador-2005667517";
        java.lang.Long _solicitaEtiquetas_idServico = Long.valueOf(2849381449687498610l);
        java.lang.Integer _solicitaEtiquetas_qtdEtiquetas = Integer.valueOf(25641760);
        java.lang.String _solicitaEtiquetas_usuario = "_solicitaEtiquetas_usuario-2107242968";
        java.lang.String _solicitaEtiquetas_senha = "_solicitaEtiquetas_senha-1104279341";
        try {
            java.lang.String _solicitaEtiquetas__return = port.solicitaEtiquetas(_solicitaEtiquetas_tipoDestinatario, _solicitaEtiquetas_identificador, _solicitaEtiquetas_idServico, _solicitaEtiquetas_qtdEtiquetas, _solicitaEtiquetas_usuario, _solicitaEtiquetas_senha);
            System.out.println("solicitaEtiquetas.result=" + _solicitaEtiquetas__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitaXmlPlp...");
        java.lang.Long _solicitaXmlPlp_idPlpMaster = Long.valueOf(-8275753926916357080l);
        java.lang.String _solicitaXmlPlp_usuario = "_solicitaXmlPlp_usuario2020406581";
        java.lang.String _solicitaXmlPlp_senha = "_solicitaXmlPlp_senha-1744726618";
        try {
            java.lang.String _solicitaXmlPlp__return = port.solicitaXmlPlp(_solicitaXmlPlp_idPlpMaster, _solicitaXmlPlp_usuario, _solicitaXmlPlp_senha);
            System.out.println("solicitaXmlPlp.result=" + _solicitaXmlPlp__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validarPostagemReversa...");
        java.lang.String _validarPostagemReversa_codAdministrativo = "_validarPostagemReversa_codAdministrativo1723332121";
        java.lang.String _validarPostagemReversa_codigoServico = "_validarPostagemReversa_codigoServico1791357368";
        java.lang.String _validarPostagemReversa_cepDestinatario = "_validarPostagemReversa_cepDestinatario-638112419";
        java.lang.String _validarPostagemReversa_idCartaoPostagem = "_validarPostagemReversa_idCartaoPostagem1894925442";
        br.com.correios.bsb.sigep.master.bean.cliente.ColetaReversa _validarPostagemReversa_coleta = new br.com.correios.bsb.sigep.master.bean.cliente.ColetaReversa();
        _validarPostagemReversa_coleta.setCklist("Cklist1403950331");
        _validarPostagemReversa_coleta.setDescricao("Descricao-1426276792");
        java.util.List<java.lang.String> _validarPostagemReversa_coletaDocumento = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validarPostagemReversa_coletaDocumentoVal1 = "_validarPostagemReversa_coletaDocumentoVal1521196069";
        _validarPostagemReversa_coletaDocumento.add(_validarPostagemReversa_coletaDocumentoVal1);
        _validarPostagemReversa_coleta.getDocumento().addAll(_validarPostagemReversa_coletaDocumento);
        _validarPostagemReversa_coleta.setIdCliente("IdCliente-130137961");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.Produto> _validarPostagemReversa_coletaProduto = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.Produto>();
        br.com.correios.bsb.sigep.master.bean.cliente.Produto _validarPostagemReversa_coletaProdutoVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.Produto();
        _validarPostagemReversa_coletaProdutoVal1.setCodigo("Codigo-2019260481");
        _validarPostagemReversa_coletaProdutoVal1.setQtd("Qtd1088734360");
        _validarPostagemReversa_coletaProdutoVal1.setTipo("Tipo1145552721");
        _validarPostagemReversa_coletaProduto.add(_validarPostagemReversa_coletaProdutoVal1);
        _validarPostagemReversa_coleta.getProduto().addAll(_validarPostagemReversa_coletaProduto);
        br.com.correios.bsb.sigep.master.bean.cliente.Remetente _validarPostagemReversa_coletaRemetente = new br.com.correios.bsb.sigep.master.bean.cliente.Remetente();
        _validarPostagemReversa_coletaRemetente.setBairro("Bairro-1713730250");
        _validarPostagemReversa_coletaRemetente.setCep("Cep156215277");
        _validarPostagemReversa_coletaRemetente.setCidade("Cidade-529851401");
        _validarPostagemReversa_coletaRemetente.setComplemento("Complemento98606562");
        _validarPostagemReversa_coletaRemetente.setDdd("Ddd-172474950");
        _validarPostagemReversa_coletaRemetente.setEmail("Email-379502794");
        _validarPostagemReversa_coletaRemetente.setLogradouro("Logradouro-807949119");
        _validarPostagemReversa_coletaRemetente.setNome("Nome159767615");
        _validarPostagemReversa_coletaRemetente.setNumero("Numero306890661");
        _validarPostagemReversa_coletaRemetente.setReferencia("Referencia1689475272");
        _validarPostagemReversa_coletaRemetente.setTelefone("Telefone-40220376");
        _validarPostagemReversa_coletaRemetente.setUf("Uf226844593");
        _validarPostagemReversa_coletaRemetente.setCelular("Celular1780405000");
        _validarPostagemReversa_coletaRemetente.setDddCelular("DddCelular15291364");
        _validarPostagemReversa_coletaRemetente.setIdentificacao("Identificacao-322302409");
        _validarPostagemReversa_coletaRemetente.setSms("Sms796996884");
        _validarPostagemReversa_coleta.setRemetente(_validarPostagemReversa_coletaRemetente);
        _validarPostagemReversa_coleta.setTipo("Tipo392375592");
        _validarPostagemReversa_coleta.setValorDeclarado("ValorDeclarado116296621");
        _validarPostagemReversa_coleta.setAg("Ag927682836");
        _validarPostagemReversa_coleta.setAr(Integer.valueOf(477146827));
        _validarPostagemReversa_coleta.setCartao("Cartao2050736478");
        _validarPostagemReversa_coleta.setNumero(Integer.valueOf(169289793));
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.Objeto> _validarPostagemReversa_coletaObjCol = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.Objeto>();
        br.com.correios.bsb.sigep.master.bean.cliente.Objeto _validarPostagemReversa_coletaObjColVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.Objeto();
        _validarPostagemReversa_coletaObjColVal1.setDesc("Desc-1458529147");
        _validarPostagemReversa_coletaObjColVal1.setEntrega("Entrega1019276788");
        _validarPostagemReversa_coletaObjColVal1.setId("Id-774849473");
        _validarPostagemReversa_coletaObjColVal1.setItem("Item1247046925");
        _validarPostagemReversa_coletaObjColVal1.setNum("Num472875701");
        _validarPostagemReversa_coletaObjCol.add(_validarPostagemReversa_coletaObjColVal1);
        _validarPostagemReversa_coleta.getObjCol().addAll(_validarPostagemReversa_coletaObjCol);
        _validarPostagemReversa_coleta.setServicoAdicional("ServicoAdicional1985497820");
        java.lang.String _validarPostagemReversa_usuario = "_validarPostagemReversa_usuario-896910085";
        java.lang.String _validarPostagemReversa_senha = "_validarPostagemReversa_senha623843420";
        try {
            java.lang.Boolean _validarPostagemReversa__return = port.validarPostagemReversa(_validarPostagemReversa_codAdministrativo, _validarPostagemReversa_codigoServico, _validarPostagemReversa_cepDestinatario, _validarPostagemReversa_idCartaoPostagem, _validarPostagemReversa_coleta, _validarPostagemReversa_usuario, _validarPostagemReversa_senha);
            System.out.println("validarPostagemReversa.result=" + _validarPostagemReversa__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaCliente...");
        java.lang.String _buscaCliente_idContrato = "_buscaCliente_idContrato-104184010";
        java.lang.String _buscaCliente_idCartaoPostagem = "_buscaCliente_idCartaoPostagem847466677";
        java.lang.String _buscaCliente_usuario = "_buscaCliente_usuario269170954";
        java.lang.String _buscaCliente_senha = "_buscaCliente_senha-1185961935";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP _buscaCliente__return = port.buscaCliente(_buscaCliente_idContrato, _buscaCliente_idCartaoPostagem, _buscaCliente_usuario, _buscaCliente_senha);
            System.out.println("buscaCliente.result=" + _buscaCliente__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaPagamentoEntrega...");
        java.lang.String _buscaPagamentoEntrega_usuario = "_buscaPagamentoEntrega_usuario-1805933239";
        java.lang.String _buscaPagamentoEntrega_senha = "_buscaPagamentoEntrega_senha-1559674746";
        java.lang.String _buscaPagamentoEntrega_contrato = "_buscaPagamentoEntrega_contrato1971615236";
        java.lang.String _buscaPagamentoEntrega_dataInicio = "_buscaPagamentoEntrega_dataInicio-1266313129";
        java.lang.String _buscaPagamentoEntrega_dataFim = "_buscaPagamentoEntrega_dataFim-184404387";
        java.lang.String _buscaPagamentoEntrega_etiqueta = "_buscaPagamentoEntrega_etiqueta-485404830";
        try {
            java.lang.String _buscaPagamentoEntrega__return = port.buscaPagamentoEntrega(_buscaPagamentoEntrega_usuario, _buscaPagamentoEntrega_senha, _buscaPagamentoEntrega_contrato, _buscaPagamentoEntrega_dataInicio, _buscaPagamentoEntrega_dataFim, _buscaPagamentoEntrega_etiqueta);
            System.out.println("buscaPagamentoEntrega.result=" + _buscaPagamentoEntrega__return);

        } catch (ErroMontagemRelatorio_Exception e) {
            System.out.println("Expected exception: ErroMontagemRelatorio has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitarPostagemScol...");
        java.lang.Integer _solicitarPostagemScol_codAdministrativo = Integer.valueOf(1562557904);
        java.lang.String _solicitarPostagemScol_xml = "_solicitarPostagemScol_xml-1447301706";
        java.lang.String _solicitarPostagemScol_usuario = "_solicitarPostagemScol_usuario1933393109";
        java.lang.String _solicitarPostagemScol_senha = "_solicitarPostagemScol_senha358683612";
        try {
            java.lang.String _solicitarPostagemScol__return = port.solicitarPostagemScol(_solicitarPostagemScol_codAdministrativo, _solicitarPostagemScol_xml, _solicitarPostagemScol_usuario, _solicitarPostagemScol_senha);
            System.out.println("solicitarPostagemScol.result=" + _solicitarPostagemScol__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaServicos...");
        java.lang.String _buscaServicos_idContrato = "_buscaServicos_idContrato770289921";
        java.lang.String _buscaServicos_idCartaoPostagem = "_buscaServicos_idCartaoPostagem-2074434841";
        java.lang.String _buscaServicos_usuario = "_buscaServicos_usuario-849029362";
        java.lang.String _buscaServicos_senha = "_buscaServicos_senha1292883641";
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _buscaServicos__return = port.buscaServicos(_buscaServicos_idContrato, _buscaServicos_idCartaoPostagem, _buscaServicos_usuario, _buscaServicos_senha);
            System.out.println("buscaServicos.result=" + _buscaServicos__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking obterMensagemParametrizada...");
        java.lang.Short _obterMensagemParametrizada_id = Short.valueOf((short)-9348);
        br.com.correios.bsb.sigep.master.bean.cliente.MensagemParametrizadaTO _obterMensagemParametrizada__return = port.obterMensagemParametrizada(_obterMensagemParametrizada_id);
        System.out.println("obterMensagemParametrizada.result=" + _obterMensagemParametrizada__return);


        }
        {
        System.out.println("Invoking buscaOpcoes...");
        java.util.List<java.lang.String> _buscaOpcoes_listaObjetos = new java.util.ArrayList<java.lang.String>();
        java.lang.String _buscaOpcoes_listaObjetosVal1 = "_buscaOpcoes_listaObjetosVal-830879223";
        _buscaOpcoes_listaObjetos.add(_buscaOpcoes_listaObjetosVal1);
        java.lang.String _buscaOpcoes_tipoResultado = "_buscaOpcoes_tipoResultado71556768";
        java.lang.String _buscaOpcoes_usuario = "_buscaOpcoes_usuario391232231";
        java.lang.String _buscaOpcoes_senha = "_buscaOpcoes_senha1031728989";
        try {
            java.lang.String _buscaOpcoes__return = port.buscaOpcoes(_buscaOpcoes_listaObjetos, _buscaOpcoes_tipoResultado, _buscaOpcoes_usuario, _buscaOpcoes_senha);
            System.out.println("buscaOpcoes.result=" + _buscaOpcoes__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
